### ISSUE TITLE
Do I need both the Tilt Sensor and the Multi-Sensor? 

### ISSUE THREAD

**Issue by AHrubik** [brbeaird/SmartThings_MyQ#10]
The Samsung Smartthings multi-sensor says it has a tilt sensor and accelerometer. Do I still need another tilt sensor as well or will the one multi-sensor do?

https://www.amazon.com/dp/B0118RQW3W/ref=psdc_7459508011_t3_B01MRZB0NT

**Comment by brbeaird** [comment]
Nope, that one will do. That said, I strongly suggest you set it up in the MyQ SmartApp with only the Tilt Sensor and NOT the accelerometer feature. For whatever reason, that piece of it is pretty buggy, and I don't have one to fully test it out.
