### ISSUE TITLE
Status Offline in Google Home App

### ISSUE THREAD

**Issue by jflowers** [brbeaird/SmartThings_MyQ#100]
I can use it from both the smarthing apps, I have a sensor setup with it. I cannot get it to work with Google Home/Assistant. In the Google Home app it shows as Not Responding and Offline(see screenshot below)

https://photos.app.goo.gl/8YVTEtpCJZT3n3yHA
![image](https://user-images.githubusercontent.com/214084/83259402-fd437400-a185-11ea-9cff-6e48a92399d9.png)

What more info is needed? How can I help?

**Comment by brbeaird** [comment]
I wish I could help. I've always had issues with Google, but their app does not give any real indication on what is wrong. Amazon devices seem to work a bit better.
