### ISSUE TITLE
Connect with IFTTT virtual sensor for light status.

### ISSUE THREAD

**Issue by jmason888** [brbeaird/SmartThings_MyQ#101]
Would it possible for the Light Controller to connect with an IFTTT-based virtual switch/sensor the way the Garage Door controller does?  Or is there a more elegant way to do this, like making a virtual switch capability on the child device visible to IFTTT for status reporting purposes?

**Comment by brbeaird** [comment]
You can do it more simply than that - just create a couple IFTTT applets that interact with the light device directly:

- When MyQ light turns on, turn on the SmartThings light device
- When MyQ light turns off, turn off the SmartThings light device

Sometimes, that will result in two event logs in the SmartThings event history, but if the action originates from the MyQ app, it does a nice job keeping the SmartThings device in sync.
