### ISSUE TITLE
Automation no longer working

### ISSUE THREAD

**Issue by benji1077** [brbeaird/SmartThings_MyQ#102]
beaird - love the work and the coding! Something far out of my reach. Here is my issue - for the past 3 years I have been using this build with my Smartthings and automation for my garage doors. Worked like a charm! With the update build, I deleted the "Garage Door Open" device handler as the directions said it wasn't needed, but now no automation when I approach my house. I have deleted and reinstalled everything I can think of to get it working, but nothing! Is there a way I can add back in the open/close device handlers to see if that will fix it back?

**Comment by brbeaird** [comment]
It won't hurt to have all the device handlers. You might also check the logs in the IDE to see if you're getting any error messages. I assume you're still trying to do this with the Classic app - things are still not quite working in the new app.

**Comment by benji1077** [comment]
> It won't hurt to have all the device handlers. You might also check the logs in the IDE to see if you're getting any error messages. I assume you're still trying to do this with the Classic app - things are still not quite working in the new app.

Do you have links to the device handlers? Can’t find them in the resources.

**Comment by brbeaird** [comment]
https://github.com/brbeaird/SmartThings_MyQ

Scroll down to the "code needed" section.
