### ISSUE TITLE
MyQ Lite (v3.1.2) login Error

### ISSUE THREAD

**Issue by D0ubl3-R** [brbeaird/SmartThings_MyQ#103]
This evening my garage door opened for no reason or automation trigger. Ever since that, MyQ Lite hasn't worked and returns an error "Warning: MyQ command failed due to bad login" anyone else experiencing same or similar error? Any suggestions to resolve?

I have already attempted to re-sign in using the MyQ credentials and returns a login Error. I am able to login to myq online with the same credentials.

**Comment by nizarsq** [comment]
I have the same issue. Tried to reinstall and got same issue.

**Comment by nizarsq** [comment]
@brbeaird any idea what is going on? Thanks

**Comment by brbeaird** [comment]
Yes, indeed. Mine is also dead. I’m busy tonight but will see what I can
find out tomorrow. I’ll also keep an eye on other integrations as I imagine
they’ll run into the same issue.

**Comment by feartheclown** [comment]
I have some troubleshooting info I think may be beneficial. First, mine broke last night as well. I updated to the latest version 3.1.2 and was continually getting the bad login error.

I've managed to get it to login 3 different times now though and I think I've nailed down the steps on how to recreate that.

1. Get into your MyQ account and change the password.
2. Get into IDE > SmartApps > MyQ Lite and run the Simulator.
3. Rerun the login over and over again until it finally allows you to login.
4. Once logged in via the simulator leave it, go to your Smartthings Classic app and try and login, redo it over and over if it fails.

I've had a mixed result from there. The reason I've done it multiple times is I haven't been able to get it to create the Garage as a lock I can tie into a Scene to control via Google Home. It DOES create a controllable Garage door in Smartthings though.

Finally, this 4th time that I just did this it added this error at the end of the app:
There was a problem updating devices:
java.lang.NullPointerException: Cannot get
property 'deviceNetworkId' on null object.
Line Number: unknown
Last Successful step: Sensor Indexing

Interestingly MyQ Lite remains installed, it lets me see my Garage Door to add it but fails with this same error every time.

**Comment by brbeaird** [comment]
Found the issue. Username and password attributes are now case sensitive and begin with capital letters.

I pushed an update to the SmartApp code to fix it. You'll want to grab that and update yours to get working again.

**Comment by darkarena1** [comment]
Thanks for the quick response.  Will this be available on the community installer soon?

**Comment by darkarena1** [comment]
never mind, it’s there..

**Comment by nizarsq** [comment]
> Found the issue. Username and password attributes are now case sensitive and begin with capital letters.
> 
> I pushed an update to the SmartApp code to fix it. You'll want to grab that and update yours to get working again.

Amazing! It's working now. Thank you

**Comment by TTVert** [comment]
Forgive the ignorance here. I see the two files that mention the password case issue but how can I apply these?  Set this up some time ago and don't remember the details.

Dave

**Comment by feartheclown** [comment]
Excellent BrBeaird! You rock!!! It works even better than before for me, I
think I was on an older version, but I didn't even have to link a scene
from Smartthings to Google for voice commands, I just straight have a
switch in Google now.

**Comment by GHN1013** [comment]
Thanks @brbeaird.  This is one of the best smart app out there with it’s integration.  Very nicely done sir!

**Comment by D0ubl3-R** [comment]
> Found the issue. Username and password attributes are now case sensitive and begin with capital letters.
> 
> I pushed an update to the SmartApp code to fix it. You'll want to grab that and update yours to get working again.

Thanks for the quick response & resolution. Seems to be back up and running after updating!

**Comment by rogelioleon0221** [comment]
How do you update the Smart things community installer to v1.1?

**Comment by TTVert** [comment]
> Forgive the ignorance here. I see the two files that mention the password case issue but how can I apply these? Set this up some time ago and don't remember the details.
> 
> Dave

To answer my own question and perhaps help someone else (Because in a year I'll forget again) I just went ahead and manually updated the SmartApp and requisite device handlers in [SmartThings IDE](https://us.account.samsung.com/accounts/v1/ST/signInGate?response_type=code&client_id=4dt548jm01&redirect_uri=https:%2F%2Faccount.smartthings.com%2FssoCallback&goBackURL=https:%2F%2Faccount.smartthings.com%2Flogin&state=lhtjlkjh94k8n7u8hcsvfbd7mk5tag4rp91aq3sv4bclt7revdivrmfbp64thjaf&countryCode=&locale=en&gBtnYN=N).  I also set up the auto sync of the gifhub repository but I'm not 100 % sure if that it automatic or if i need to manually sync it.

**Comment by GHN1013** [comment]
Not sure if you needed to do this but I did: after I updated the MyQ Lite Smart App in SmartThings IDE site, it didn’t sync the MyQ Lite app in SmartThings app itself. So I had to remove the Garage Door Opener device and then remove the MyQ app in SmartThings and then reinstall it back in to make it sync.  Hope this helps.

**Comment by bobs619** [comment]
Did the update.  Now, the opener and closer devices are not working.  Pls advise @brbeaird

**Comment by brbeaird** [comment]
@bobs619  You may need to delete the open/close momentary devices and then tap through the door setup process in the SmartApp again. They can occasionally lose their relation to the doors.

**Comment by bobs619** [comment]
@brbeaird got the garage to open and close via the "Garage Door Opener" device.  

These devices still don't work:
- "Garage Door Opener _Opener_" 
- "Garage Door Opener _Closer_" 

No biggie.  Using the  "Garage Door Opener" device will suffice

**Comment by yiweiyu32** [comment]
Mine is working again now. Really appreciate the fast turnaround on this!

**Comment by sunburnt24** [comment]
I'm still have issues with logging in after updating to 3.1.3 via the IDE. I uninstalled and reinstalled. Any ideas on what I should try?

**Comment by ColeJ1283** [comment]
Is there any update on getting the myq garage door working

**Comment by brbeaird** [comment]
I'm working on it - making good progress. Posting more detailed updates here: https://community.smartthings.com/t/release-myq-lite-door-and-lamp-control-for-liftmaster-chamberlain/49150/2327

**Comment by ColeJ1283** [comment]
Thank you

**Comment by ColeJ1283** [comment]
So I updated the st community installer in smartthings do I need to do
anything else? I tried logging in and it still didn't let me login

**Comment by ColeJ1283** [comment]
Can you let me know the steps I need to follow to get the myq garage door
working again?

Thanks

**Comment by brbeaird** [comment]
Read the update instructions here: https://github.com/brbeaird/SmartThings_MyQ

There is no login anymore - you need to generate a token separately first.

**Comment by ColeJ1283** [comment]
So I went through the steps and then open the smart app it says I'm missing
the myq token app settings

**Comment by liviuaugustin** [comment]
Worked very easy and fast. Thank you!!!! Great work! Very good instructions.

**Comment by ColeJ1283** [comment]
so i went through the steps to get a token. im using a chrome book so i
downloaded the linux file. in step 2.2 i opened the terminal and tried
typing in  chmod u+x myqtokengenerator-macos  but it gave me an error. then
i tried  ./myqtokengenerator-macos  but that didnt work either. do you know
if i need to do something different for a chrome book?

thanks for your help
