### ISSUE TITLE
Link for Momentary Button Tile Doesn't Work

### ISSUE THREAD

**Issue by rgn2000** [brbeaird/SmartThings_MyQ#107]
Hi,

I'm getting a 404 Error when clicking on the link for Momentary Button Tile.

Thank you,
Rob

**Comment by brbeaird** [comment]
My bad - that has been replaced with Virtual Switch. I have updated the readme doc .

https://raw.githubusercontent.com/brbeaird/SmartThings_MyQ/master/devicetypes/brbeaird/virtual-switch.src/virtual-switch.groovy

**Comment by rgn2000** [comment]
Thank you. Does this work for both opening and closing the door? The SmartThings apps seems to only want to close. I also can't get Google Assistant to understand to turn on or turn off Rob's Garage Door (the actual title of my door). Google Assistant is linked to SmartThings.

**Comment by brbeaird** [comment]
You should get two switches created - one to open the door and one to close the door.

Google is a tricky one, honestly. I know of several people who have had trouble with it, and I'm not really sure how to get it to work.

**Comment by rgn2000** [comment]
I now see the two switches, but still nothing in Google. Do you know if this setup requires the SmartThings Hub? I don't have that as this is the only device that I have. It's all set up in my SmartThings app and it seems like it should work with Assistant as I have added SmartThings via Google Home and Google Assistant. But if the Hub is required than I am out of luck I guess.

**Comment by brbeaird** [comment]
I wouldn't think so, but I am not totally sure. You might also make sure
you're using the newest Google integration (there is a legacy version that
will be retired soon).

**Comment by rgn2000** [comment]
What do you mean, newest Google Integration? I am using the Google Assistant app on my Pixel. It's been updated too.

**Comment by brbeaird** [comment]
I just saw a notice on the forums earlier referencing the fact that the
"legacy" Google integration was being retired. I'm not too sure what that
means, honestly, as I don't use it.
