### ISSUE TITLE
New Installation - nothing happens

### ISSUE THREAD

**Issue by uncdubdiver** [brbeaird/SmartThings_MyQ#108]
Hello,
I don't know if it's my account or what, but when I copy the code, put in the SmartApp, put in the Device Type Handler, and then go through an link my account within the ST app, I hit the Done button and it flashes quickly on the screen and goes back to the ST SmartApps page.  I know the username/password work for the login of the MyQ app, but it's like my account doesn't have access to the API or something.
Thanks for the help.

**Comment by brbeaird** [comment]
If you check live logging in the SmartThings web IDE while you try it, you should hopefully get a more helpful error message.
