### ISSUE TITLE
Google Home

### ISSUE THREAD

**Issue by jkhilbun** [brbeaird/SmartThings_MyQ#11]
How do you make this work with  Google Home?

**Comment by brbeaird** [comment]
I don't have one myself, but people have said it works. I imagine you get Google to discover the device, then you just say "turn on the garage door" to get it to open.

**Comment by jkhilbun** [comment]
Thank you

 

 

Ken Hilbun

Office   765-474-8204

Cell:      765-427-5500

Fax:       765-609-8031

**Comment by liviuaugustin** [comment]
you can say : "garage door ON/OFF" , works for me ;)

**Comment by jkhilbun** [comment]
Did you set up two devices can Google home or what 
Thank you

⁣

Ken Hilbun
Office  765-474-8204
Cell:      765-427-5500
Fax:       765-609-8031​


-------- Original Message --------

**Comment by tHeReAlSnAkE** [comment]
I set up two devices and they just have different names. Main Door and Side Door I think.
