### ISSUE TITLE
Switches Inoperative?

### ISSUE THREAD

**Issue by richleyh** [brbeaird/SmartThings_MyQ#111]
Hi! First, thanks so much for maintaining this - I've used it for a couple of years or so and love it. Recently, I've had issues with things not working, so I completely uninstalled and re-installed everything. I see that virtual switches have replaced the momentary switches. I can't seem to get my switches to activate through the ST app. Also, both the "opener" switch and the "closer" switch default to "on", so I'm uncertain what the intended use was meant to be. To open the door, do I turn off the closer? Or turn off, then turn back on again the opener switch? Regardless of the intended use, where I'm at now, any attempt to toggle either of the switches results in a spinning logo in the ST app, finally timing out with an error saying it's unable to connect. I can control the door well through the MyQ app, and all DHs and the smart app are up-to-date. I've uninstalled and re-installed the devices within the smart app a couple of times now, but haven't been able to overcome this obstacle. Any ideas? Thanks again!

**Comment by richleyh** [comment]
Just an addendum to the above message - the buttons in the ST (new version) still don't work, BUT my goal was to use them in Webcore and in Actiontiles, and both of these seem to work flawlessly, so, as as I'm concerned, I'm good. However, if you;d like me to help remedy the smart app's behavior in ST, I'm glad to help if you wish. Otherwise, thanks again for providing this functionality! :)

**Comment by brbeaird** [comment]
It sounds like you're using the no-sensor version of the app. If that's the case, the switches really do not work well in the new app. Hopefully that will change in the near future, but for now, all I can suggest is to wait it out or else grab a sensor for the door and try that.
