### ISSUE TITLE
Unable to Program Automations to close door in Smartthings

### ISSUE THREAD

**Issue by LanesBrokenSki** [brbeaird/SmartThings_MyQ#118]
There are only two options for the Garage door setting in Smartthings when programming an automation.  Open and Closed.
 When selecting Closed, there is an error trying to save the automation.

Past automation that was setup has a "close" option that worked in the past.
![Door Automation](https://user-images.githubusercontent.com/51099317/107124010-a2aafd80-6866-11eb-9f48-5f92c9be387f.png)

**Comment by brbeaird** [comment]
I still have all my garage automations set up in Smart Lighting for this reason and other weirdness.

One thing I will say is it doesn't hurt anything to send a "close" command to the door if the door is already closed. MyQ will receive the command, see that the door is already closed, and do nothing. That may simplify your rule in that you don't need ST to check if it's already closed or not.

**Comment by GHN1013** [comment]
> I still have all my garage automations set up in Smart Lighting for this reason and other weirdness.
> 
> One thing I will say is it doesn't hurt anything to send a "close" command to the door if the door is already closed. MyQ will receive the command, see that the door is already closed, and do nothing. That may simplify your rule in that you don't need ST to check if it's already closed or not.

Hi Brad. I’ve actually set up “close” commands and integrated into some automations that has been working fine up until this evening.  Weirdly, I can still open the garage door using the app, but when intr closing it, I now get this error: Java.net.Sockettimeoutexception: Read Timed out.

Any ideas what this is now?

**Comment by Taasadi** [comment]
> There are only two options for the Garage door setting in Smartthings when programming an automation. Open and Closed.
> When selecting Closed, there is an error trying to save the automation.
> 
> Past automation that was setup has a "close" option that worked in the past.
> ![Door Automation](https://user-images.githubusercontent.com/51099317/107124010-a2aafd80-6866-11eb-9f48-5f92c9be387f.png)

try to use off, this what I used for Scene setup.

**Comment by LanesBrokenSki** [comment]
I get a Network Error message every time I try to Add this option (On, Garage door:Closed) on either an automation or a scene. 

Corry Simkins

**Comment by brbeaird** [comment]
So in this case, I think what you need to do is simply make it turn the switch "off" and don't bother with setting door "closed." It's a bit awkward, but that should work.
