### ISSUE TITLE
Not your issue but wonder if you run into it, having to relink IFTTT to Smartthings

### ISSUE THREAD

**Issue by TTVert** [brbeaird/SmartThings_MyQ#119]
This has started happening quite a bit to me later after not happening for years. All the sudden a command that is set up in IFTTT to trigger the MYQ virtual switch isn't recognized.  if I disconnect and reconnect the applet it'll work again w/o changing anything else.  Your virtual switches always work as designed it's the IFTTT stuff that is acting up.  

Thanks much

Dave

**Comment by brbeaird** [comment]
IFTTT was having quite a few issues during March. From what I hear, things have been more stable lately.

**Comment by TTVert** [comment]
> IFTTT was having quite a few issues during March. From what I hear, things have been more stable lately.

yeah it's been fine lately.  It's annoying that I pay for IFTTT and there is ZERO support from them when their crap randomly just breaks. I had one command I had deleted and no matter what I did I could not get rid of it..  Emailed them and never heard back.
