### ISSUE TITLE
Cannot use scene/automation to close garage door

### ISSUE THREAD

**Issue by georgesc3** [brbeaird/SmartThings_MyQ#122]
This worked forever but quite a while back. When I set a scene or automation to close the door on action (me leaving), it takes the setting till the last save and then gives a “network error” which stops the save. Let me know if you need screen shots or anything else. Thank you.

**Comment by AndrewC75** [comment]
I am having the same issue. Hub v2.

**Comment by brbeaird** [comment]
I have an idea of what my be causing this. I'll see if I can play some more with the automation piece of the custom device handlers.

**Comment by georgesc3** [comment]
That fixed it for me. Very much appreciated!

Thank you,
George

On Aug 2, 2021, at 11:33 AM, Brian Beaird ***@***.***> wrote:

﻿

I have an idea of what my be causing this. I'll see if I can play some more with the automation piece of the custom device handlers.

**Comment by brbeaird** [comment]
I'll be pushing an update tomorrow that will clean up automation conditions and actions tomorrow. This really should only need "open" and "close" as automation actions.

**Comment by georgesc3** [comment]
Did you do the update, as of now it appears to be doing the opposite of what it should. It opens the door instead of closing it.

On Aug 2, 2021, at 11:22 PM, Brian Beaird ***@***.***> wrote:

﻿

I'll be pushing an update tomorrow that will clean up automation conditions and actions tomorrow. This really should only need "open" and "close" as automation actions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrbeaird%2FSmartThings_MyQ%2Fissues%2F122%23issuecomment-891488568&data=04%7C01%7C%7C9564ff7d8c604e52275008d9562df0de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637635577577628458%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7jqJ5wbCRm%2FSvQPjZqbK%2FeOzHZ8uZ59Dw7joO9TZaeQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF455HF4EVH6QM5BTJKONBDT25OHXANCNFSM5BINNL3Q&data=04%7C01%7C%7C9564ff7d8c604e52275008d9562df0de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637635577577638453%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KuHbzbVrTCkWJzhYS8IRFqd8n0L7MokCXPZOELETXWk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9564ff7d8c604e52275008d9562df0de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637635577577648450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YQEhr61k4hrCf58zZapEI9b1WuLIoNTYL8HqsijVOQA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C9564ff7d8c604e52275008d9562df0de%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637635577577648450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HGTKCYwlagrfN%2B17SR%2FTXfMb4XGy7P9hUQJBg4%2FGGFY%3D&reserved=0>.

**Comment by brbeaird** [comment]
No, have not pushed anything yet. Still playing with it. My assumption is
that what's out there is basically totally broken. Hoping I get more time
tonight to finish it out.

**Comment by brbeaird** [comment]
I just pushed out an update that simplifies automation options down to only door control. This cleans things up quite a bit, but if you already have automations created that used the on/off or other actions, you will need to edit those to now use the simple door open/close actions.

**Comment by georgesc3** [comment]
Thanks, it appears it changed for scenes I’m not automation. I have not tested yet

On Aug 5, 2021, at 12:21 AM, Brian Beaird ***@***.***> wrote:

﻿

I just pushed out an update that simplifies automation options down to only door control. This cleans things up quite a bit, but if you already have automations created that used the on/off or other actions, you will need to edit those to now use the simple door open/close actions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrbeaird%2FSmartThings_MyQ%2Fissues%2F122%23issuecomment-893153261&data=04%7C01%7C%7Cf968c2d032ec493160bf08d957c88ca0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637341125329614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=61q0541jQv34BG9ULvlqiPRcsNlPMvV3XUePabCwhvY%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF455HBESCFFZX4MXQTEPDDT3IGV5ANCNFSM5BINNL3Q&data=04%7C01%7C%7Cf968c2d032ec493160bf08d957c88ca0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637341125339608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dcSCb%2Fz3A%2FbJgGFvbMyr625ff7MSalnQMFq31X6aeqM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf968c2d032ec493160bf08d957c88ca0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637341125339608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OJDQLykrs4Ay8Ne2CTr9wVOtivSunb%2FKPBOF7fHApuQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cf968c2d032ec493160bf08d957c88ca0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637341125349606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uyHeC4daPKB75iNzGjOfLbLXxnGF71%2F%2BCeQ2fseMrQM%3D&reserved=0>.

**Comment by georgesc3** [comment]
Correction, just tried it again and the dialogs are the same for scene and automation. I’ll test today to confirm it works.

Thank you,
George

On Aug 5, 2021, at 9:15 AM, George Scott ***@***.***> wrote:

﻿
Thanks, it appears it changed for scenes I’m not automation. I have not tested yet

On Aug 5, 2021, at 12:21 AM, Brian Beaird ***@***.***> wrote:

﻿

I just pushed out an update that simplifies automation options down to only door control. This cleans things up quite a bit, but if you already have automations created that used the on/off or other actions, you will need to edit those to now use the simple door open/close actions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrbeaird%2FSmartThings_MyQ%2Fissues%2F122%23issuecomment-893153261&data=04%7C01%7C%7Cb8b08d4fd0b04841b4b208d958130f5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637661144566660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gVDfAmrf9eqfAp3VTQdpzfL2yk%2BoFWszHSu%2BirpQDyk%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF455HBESCFFZX4MXQTEPDDT3IGV5ANCNFSM5BINNL3Q&data=04%7C01%7C%7Cb8b08d4fd0b04841b4b208d958130f5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637661144576655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WoC6kzoEsvOGomgqmq4pxCgXMhrNcvSwV0x7Xg5RuQE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb8b08d4fd0b04841b4b208d958130f5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637661144576655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dtXFLIbJVJmmODjcUl92KpjQKyzDDqC2CGiYSpqWmLo%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cb8b08d4fd0b04841b4b208d958130f5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637637661144586650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tAbCzzboiTmxRwBFos0T%2FOdbUavKGN%2FXtpJFYeCdht4%3D&reserved=0>.
