### ISSUE TITLE
Device handler update via repo...

### ISSUE THREAD

**Issue by rashuge** [brbeaird/SmartThings_MyQ#123]
I kept getting an update available message.  I realized that the device handlers had an update as well besides the SmartApp.  The SmartApp is updated to newest via repository.  When I attempt to update the device handlers via the repo I get the attached error message and cannot quite figure out what is going on.

![image](https://user-images.githubusercontent.com/42649583/128410857-d7cef978-f5d6-4499-98af-ad034c0ecc1c.png)

**Comment by brbeaird** [comment]
Mine seems to work ok. Maybe try deleting and re-adding the github repo entry?

**Comment by rashuge** [comment]
I did the disconnect of the repos, deleted the repo and reconnected.  Still the same issue.  I put in a screen shot of the update repo screen.  I have selected all new objects and attempted the publish and get that issue.

![image](https://user-images.githubusercontent.com/42649583/128414563-baed46c3-b274-4340-99d9-59a9bfaaa585.png)

**Comment by brbeaird** [comment]
Not sure about that then. You could try a support ticket with SmartThings?

**Comment by rashuge** [comment]
I did a delete of the device handlers and then a reinstall using the community installer and it appears to have taken the newest version now at least.  I will deal with the situation in the future if it comes up again.  Thanks for such quick follow up.
