### ISSUE TITLE
Newest MyQ Update 8/05 keeps getting error message 

### ISSUE THREAD

**Issue by GHN1013** [brbeaird/SmartThings_MyQ#124]
Hi Brian,  I tried updating the MyQ Lite app using Update from Repo on Smarthings IDE page and I keep getting error:  
Error
500: Internal Server Error
URI
/ide/device/doRepoUpdates
Reference Id
adb16107-……
Date
Thu Aug 12 05:45:54 UTC 2021

**Comment by brbeaird** [comment]
A few people have had this issue - it seems to be an issue with some people affecting the SmartThings/GitHub integration. Others have had success by either using the Community Installer or just doing it manually. You could always try a support ticket with SmartThings, though.

**Comment by GHN1013** [comment]
Oh ok.  Wasn’t sure if it was something related to the update itself.  I’ve had successes in past with updates, even as recently as your last update last month, so I don't think it’s the GitHub/ST integration.  To install it manually, just follow same instructions you have for copying code and pasting over existing code?

**Comment by brbeaird** [comment]
Yes, copy/paste over the existing code will do it. I know the it updates from SmartThings are still working for this (including my own), so I'm not really sure what causes that error. If anyone ever figures it out, and it's something I can change in this repository itself, let me know.

**Comment by GHN1013** [comment]
Thank you Brian.  I’ll try to copy/paste code in manually.
