### ISSUE TITLE
Myq with myq sensors 

### ISSUE THREAD

**Issue by cqqlav** [brbeaird/SmartThings_MyQ#13]
hello, when I am setting it up it doesn't see my sensors say there are no devices of this capability. Please help

**Comment by brbeaird** [comment]
Are your sensors showing up in SmartThings as contact sensors? You've got separate sensors for this and not just the ones that came with MyQ, right?

**Comment by cqqlav** [comment]
No I am using myq sensor that came with myq and it not showing up in
SmartThings. I used toy use not the lite version and it worked. But removed
it and installed your color.

**Comment by cqqlav** [comment]
Got it. Thank you for letting me know
