### ISSUE TITLE
After update able to view status but can no longer open/close from Smartthings

### ISSUE THREAD

**Issue by cav22** [brbeaird/SmartThings_MyQ#131]
I have successfully updated the token into the app settings and Smartthings now shows the status of the door when manually opening but when triggering the open/close operation from Smartthings the door does not open or close.

**Comment by teba-home** [comment]
Did you go back into the myq smartapp and update the devices? All you need to do is select the device and click through. No need to change anything

**Comment by cav22** [comment]
I am leaving clicked into the devices but must not have clicked through the next screens. Delete the issue as it is working. Problem between the chair and the phone screen....

Thanks
