### ISSUE TITLE
Can't Login with MyQ Credentials on MyQ API V5 (9/10/21)

### ISSUE THREAD

**Issue by 80am33** [brbeaird/SmartThings_MyQ#132]
The app won't take me log in using the user name and password that I know are correct. I uninstalled the devices and tried to reinstall and still no joy.

**Comment by schpeen** [comment]
I cant seem to figure any of this out as well. I am a mac user downloaded the file but running those commands in terminal dont work. Not sure what he means by directory of utility ....I am lost lol 

Usally good at this stuff but this one I am lost.

**Comment by 80am33** [comment]
I just copied and pasted the code into smarthings via the website

**Comment by schpeen** [comment]
> I just copied and pasted the code into smarthings via the website. That’s how it worked up until now. Now I can’t log in to get to the set up part. 🤷🏼‍♂️

I finally got it to work. It was much easier to get the refresh token using windows. I am all good now and its working. Make sure to follow his new instructions on getting the refresh token.
