### ISSUE TITLE
MyQ Lite /  Samsung Multi purpose sensor issue with Network ID

### ISSUE THREAD

**Issue by Tkwomble** [brbeaird/SmartThings_MyQ#134]
![Screenshot_20210911-103009](https://user-images.githubusercontent.com/72259958/132951580-9ede3026-41cf-40ac-95ae-933b42f6d739.jpg)

Can anyone assist as I keep getting the following error and I am using a Samsung Multi purpose sensor.. The network ID on my sensor is 8BBC...

Display Name | Type | Location | Hub | Zigbee Id | Device Network Id | Status | Execution Location | Last Activity

Garage Door1 | SmartSense Multi Sensor | Home | Home Hub | 286D9700010D7C76 | 8BBC | ONLINE | Local | 2 minutes ago

**Comment by brbeaird** [comment]
Seems like somehow things got out of sync. You may just try a total reinstall.

**Comment by sredk** [comment]
Dealing with same error, tried removing everything (device handler/tilt sensor/smart app) and adding again, but ended up with same error! Any other ways to debug..
