### ISSUE TITLE
No place to update token settings

### ISSUE THREAD

**Issue by jkhilbun** [brbeaird/SmartThings_MyQ#135]
No place to update token in settings

Settings I do not see What is listed in the documentation.
Validated I am in the 4.0.
This is what I get an a settings box
Add setting definitions in the source code and then set the values here

The code that was downloaded from the web had this for defining the token Settings

appSetting "MyQToken"
I did not work so I changed it to the following and then I could capture my token 

appSetting ("MyQToken")

**Comment by ZackGen** [comment]
I have the same issue.  I attempted to uninstall and reinstall via the Community Installer.  
![Screenshot 2021-09-12 100716](https://user-images.githubusercontent.com/25972426/132990786-c2d711ae-f801-4271-bf20-39495e5667b5.jpg)

**Comment by brbeaird** [comment]
For whatever reason, that means your SmartApp update did not fully take. I would suggest you manually copy/paste, save, publish the code yourself and then see if it shows up.
