### ISSUE TITLE
myqtokengenerator-win closes

### ISSUE THREAD

**Issue by bamfuchs** [brbeaird/SmartThings_MyQ#136]
When I run the myqtokengenerator-win it asks for my MyQ email and password then it shows
Info:  Getting verification token...
Info:  Logging into MyQ...

then the window closes

**Comment by brbeaird** [comment]
Try the latest version - it shouldn't instantly close now and show what the error is.

Alternatively, you can open a command prompt and then execute it from there.

What OS version are you on?

**Comment by bamfuchs** [comment]
Windows 10

**Comment by brbeaird** [comment]
Yeah that should definitely be supported. Try the newest .exe and see what it says.

**Comment by bamfuchs** [comment]
The new on works

**Comment by brbeaird** [comment]
Awesome - good to hear.
