### ISSUE TITLE
Make latest changes compatible with Hubitat

### ISSUE THREAD

**Issue by mjacobs3761** [brbeaird/SmartThings_MyQ#138]
Hi Brian,

We use the Myq-lite on Hubitat, and obviously had the same APi issues.
Excited to see you had a fix ..

However when doing the update, it is still 3.1.3 using the hubitat application manager ..
So I decided to see if I could do manually an update, but if I use the source, I get the following error message

Metadata Error: Capability 'towertalent27877.lastActivity' not found. on line 21

**Comment by brbeaird** [comment]
That's a custom capability using the new config process in SmartThings.
That almost certainly won't work with Hubitat.

**Comment by mjacobs3761** [comment]
Hi Brian,

I know there is a rather large group of us on Hubitat using your version 3.1.3.
Are you planning to make a more agnostic version that can be used on Hubitat, or what will it take to ask/plead/entice :) you to do so?

**Comment by brbeaird** [comment]
I'll think about it but honestly not sure if I realistically have the time to handle it.
