### ISSUE TITLE
Can no longer update DTH through GitHub repository in IDE

### ISSUE THREAD

**Issue by seattleandrew** [brbeaird/SmartThings_MyQ#140]
I recently updated my MyQ token and was going through the process of updating the smart app and DTH. Smartapp updated fine but when I try to update any of the DTH it fails with this error.
![image](https://user-images.githubusercontent.com/541127/133483932-3d3ad2d9-adf9-4173-b51b-74ab7ee1f456.png)

I tried to remove the DTH and start fresh but I still can't install any of the DTH via GitHub
![image](https://user-images.githubusercontent.com/541127/133484270-551d0625-a338-40ac-b88b-6e9ba2f6650f.png)

Should I be manually copying/pasting the code instead of GitHub?

**Edit:** I found the issue. I need to only publish .groovy files and ignore everything else. Maybe a note in the setup guide until the new version using Smartthings API is established.

**Comment by brbeaird** [comment]
> I need to only publish .groovy files and ignore everything else. Maybe a note in the setup guide until the new version using Smartthings API is established.

That is a great callout. I've updated the readme - thanks.
