### ISSUE TITLE
Error creating "no sensor" version of SmartApp

### ISSUE THREAD

**Issue by bamfuchs** [brbeaird/SmartThings_MyQ#141]
When I try to make the "No Sensor" version of the app I get

No signature of method: script_app_metadata_2e5db29d_41d3_425a_9e60_d62caef424e5.metadata() is applicable for argument types: (script_app_metadata_2e5db29d_41d3_425a_9e60_d62caef424e5$_run_closure1) values: [script_app_metadata_2e5db29d_41d3_425a_9e60_d62caef424e5$_run_closure1@49644d6e] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by brbeaird** [comment]
That may be because you were pasting SmartApp code into a Device Handler or vice versa. Give it another shot.
