### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method post() on null object @line 418 (getVersionInfo)

### ISSUE THREAD

**Issue by mase1981** [brbeaird/SmartThings_MyQ#148]
1. Deleted smartapp,devices and device handlers to start from scratch. 
2. Rebooted smartthings hub. 
3. Reinstalled from repo per instructions device handlers and then smartapp.
4. On phone added smartapp
5. Get error
![Screenshot_20210925-105940](https://user-images.githubusercontent.com/3089864/134777837-b4348644-7c11-49dc-850c-626aadef6a7d.png)
Despite error there is a new smartapp in app however each time you click on it you get same error
6. checking IDE logs you see: 
7. `e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:23 AM: error java.lang.NullPointerException: Cannot invoke method post() on null object @line 418 (getVersionInfo)
e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:23 AM: info Checking for latest version...
e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:08 AM: error java.lang.NullPointerException: Cannot invoke method post() on null object @line 418 (getVersionInfo)
e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:08 AM: info Checking for latest version...`
8. attempting to remove and re add and get error: 
`e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:30 AM: error error executing uninstalled method on MyQ Lite: java.lang.NullPointerException: Cannot invoke method post() on null object
e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:30 AM: info Checking for latest version...
e5eb161c-1b00-4e97-9920-7322fbe99f91 10:47:30 AM: debug MyQ removal complete.`

**Comment by brbeaird** [comment]
I just pushed a quick fix for that in the SmartApp. Give it another shot.

**Comment by mase1981** [comment]
> I just pushed a quick fix for that in the SmartApp. Give it another shot.

That fixed it!
