### ISSUE TITLE
MyQ on Smartthings still doesn't work

### ISSUE THREAD

**Issue by wxguylit** [brbeaird/SmartThings_MyQ#149]
I ran the installer to do your latest update. I have tiles on my favorites page that both say "on" If I click the closer tile, I get a spinning icon, then the message block comes up saying it can't connect to the server, try again.

Everything worked fine before MyQ changed stuff, but now nothing works, except their app. Maybe I've missed something, but don't know what or where. This is all getting way to complicated for me. 

Is there something easy I could do, or would my life be more fulfilling if I just deleted this routine?

**Comment by brbeaird** [comment]
It should still work, but it sounds like something did not fully update like it should. Make sure you updated the app and all device handlers, then open up the SmartApp and tap through the config to ensure the devices are set up. If that still doesn't work, you may try a clean uninstall/reinstall.
