### ISSUE TITLE
Can't authenticate on mobile app

### ISSUE THREAD

**Issue by petegroome** [brbeaird/SmartThings_MyQ#150]
Hi - I've been successful on everything up to logging in on the mobile app. I've triple checked my password matches and it won't log me in. I've generated a token (which successfully generated), but there is no option on the mobile app (or the browser version) to use that option. Any help would be appreciated. Thanks.

**Comment by brbeaird** [comment]
The future version can be found here: https://github.com/brbeaird/SmartThings-MyQ-Edge
