### ISSUE TITLE
Instructions don't seem to match current SmartThings app

### ISSUE THREAD

**Issue by daviddoria** [brbeaird/SmartThings_MyQ#152]
This step in the instructions:
"10. In your SmartThings mobile app, tap Automation -> SmartApps -> Add a SmartApp. Scroll down and tap My Apps. Tap MyQ Lite."
doesn't seem in sync with the current SmartThings app. Here's what I did:

- Tap on the Automations tab
- Tap the '+', then 'Add routine'
- Tap 'Discover'
- Tap 'MyQ Lite'

**Comment by dchmelik** [comment]
Doesn't seem a way to install installer anymore.

**Comment by dchmelik** [comment]
How would one do it if one doesn't/can't have old SmartThings?

**Comment by brbeaird** [comment]
The future method can be found here: https://github.com/brbeaird/SmartThings-MyQ-Edge
