### ISSUE TITLE
Still having login error. 

### ISSUE THREAD

**Issue by zdriver984** [brbeaird/SmartThings_MyQ#153]
I updated app and handler.  Set up again with new devices found as in instructions.  It worked via voice commands and new push buttons for about 5 min.  Then login error again.  Changed password on myq app and verified login creds.   Then re-entered in myqlite.   App signs in and out with creds fine.  Myq lite still has login error.

**Comment by brbeaird** [comment]
The future version can be found here: https://github.com/brbeaird/SmartThings-MyQ-Edge
