### ISSUE TITLE
Controlling lights with Z-wave relay

### ISSUE THREAD

**Issue by Tylerspapa** [brbeaird/SmartThings_MyQ#154]
I have outside lights being controlled by a ENERWAVE Z-Wave Plus Relay.
This relay is in parallel with a single pole toggle switch.It is also controlled by a SmartThings app via a routine in the Automation section of the app
The lights are set up to come on at sunset and off at 8 PM . This schedule is used to allow people safe passage during dark
Sometimes the meeting will get over before 8PM and someone ,being energy conscious, shuts off the lights. They do this by turning the toggle switch ON which sends a power to the relay and the lights shut off ,but the problem , is that when the program reaches 8 PM it sends a signal to the relay and the lights that are off will now turn on.
I'm wondering if there is a way to solve this issue ? Can a IF and Condition be set up to sense the lights are actually on or off and make sure the lights are in the proper condition ?
I know it would be nice if I could just eliminate the switch ,but the switch needs to be in place in case someone schedules a meeting that during a time when the outside lights are not programmed . they can turn on and off via the toggle switch
Any solution would be appreciated

**Comment by N3rd7** [comment]
Hi Tylerspapa,
It might not be the solution you are looking for, but replacing the switch
with the MyQ light switch would do it, as smartthings, Alexa, MyQ itself
(controllable by ifttt) know whether the lights are on or off. And as for
any other switches, it can be controlled manually.
