### ISSUE TITLE
java.lang.NullPointerException: Cannot get property deviceNetworkld' on null object.

### ISSUE THREAD

**Issue by rocord01** [brbeaird/SmartThings_MyQ#155]
I am having an issue with linking my myq account to my SmartThings app.
See attached image for more info
![Screenshot_20220908_210118_SmartThings](https://user-images.githubusercontent.com/57117549/189250837-39404c4b-cda7-4860-b19e-865f5e30eaa9.jpg)

**Comment by brbeaird** [comment]
The future version can be found here: https://github.com/brbeaird/SmartThings-MyQ-Edge
