### ISSUE TITLE
Open and Close rather than On and Off

### ISSUE THREAD

**Issue by AHrubik** [brbeaird/SmartThings_MyQ#16]
I understand why we have say "On and Off" to activate the switch functionality but for a brief period I was able to say "Open and Close" to operate the door. I think maybe a week or two. Did you change something with the code that enable this functionality or am I losing my mind?

**Comment by brbeaird** [comment]
I haven't changed anything. If that was ever possible, it would have been a glitch on the Alexa (or Google Home - not sure which you have) side. It's never been possible for me as Alexa only uses the "Open" keyword for opening apps, not Smart Home devices.

**Comment by AHrubik** [comment]
It was Alexa. I was shocked it worked around a week or two ago when I tried it. It continued to work and I just assumed you had updated something or Amazon had enabled something on their end. I want to say it was two days ago I went to use it and it responded with the tried and true "I'm sorry ..." answer.

**Comment by brbeaird** [comment]
Interesting. You're not the first person I've heard of who has noticed this over the last year, though, for small periods of time. I assume they're always testing stuff behind the scenes, and occasionally the functionality becomes enabled here and there. Maybe this means eventually they'll unlock it? I can only hope!

**Comment by haloguy628** [comment]
Today the app did not work so I deleted it from ST and reinstalled. Before when the old app worked I could use "Alexa Open/Close Big/Small Garage" command. It also works now after the reinstall.
