### ISSUE TITLE
Stopped working and now can't add it back.

### ISSUE THREAD

**Issue by bishopmax** [brbeaird/SmartThings_MyQ#19]
MyQ for my liftmaster was working for months then stopped.  I removed this app from my smartthings.  Now I can't add it again.  I published the app for me.  I enter in my email, password, and select liftmaster.  I hit next and nothing shows up.  I am not sure why that is.  I remember this being very easy to setup the first time I did it.

**Comment by brbeaird** [comment]
This has been happening for several people over the last week. It's still working for mine, so I haven't been able to reproduce. I'm trying to find someone who can get me some packet capture while using the native MyQ app so I can try and figure out what has changed.

**Comment by bishopmax** [comment]
Let me know if there is anything I can provide.  I really miss having this feature.

**Comment by bishopmax** [comment]
Do you need a packet capture from my computer or my device?  I know how to do that from my computer.   I would need instructions to do that from my device.

**Comment by bishopmax** [comment]
I am very familiar with wireshark

**Comment by brbeaird** [comment]
I just pushed a new version. I needed to start sending SecurityToken along in the header. Give it a shot and see if it works for you.

**Comment by bishopmax** [comment]
I was able to add the new code and select my garage door, but now the smartthings app has become unresponsive.  I cant imagine that was what caused it, but the smartthings app just sits there with the wheel of sadness spinning and I never get to the menu system.  I am going to try and uninstall and reinstall the app.

**Comment by bishopmax** [comment]
okay app issue fixed.  They MyQ lite doesn't seem to save.  I get the following after trying to add it.  "Garage Door Opener:  problem creating door device (no-sensor type).  Check your IDE to make sure the brbeaird: MyW Garage Dorr Opener - NoSenser device handler is installed and published.
-------
Your AmartApp verson (2.0.2) is not the lates version (null)

I have tried to remove and re-add but it says I can't remove it since it is in use.  I have updated it and re-copied the code into the app and re-published.  Nothing has worked so far.  

Thanks for being so responsive.

**Comment by brbeaird** [comment]
That error normally means you haven't created (and published) the device type handler in your IDE. Could you double check that?

**Comment by bishopmax** [comment]
I renamed the one that was installed since I couldn’t remove it.  I added it again and published.  Same issue.

**Comment by brbeaird** [comment]
Could you get some logs in the IDE of exactly what's happening when you try to do that? Screenshots of the mobile app might also be helpful.

**Comment by bishopmax** [comment]
Thanks for getting back to me.  I will get that for you as soon as I get home from work.

**Comment by bishopmax** [comment]
Here is the log.  There are no errors on the smartapp.  I even get the green message bar that it was added successfully, but it never shows up in my inventory.  The log is from when I start up the app and try to add it.  It seems to work now, but I can’t add it to any automations since it isn’t there to be selected.

**Comment by brbeaird** [comment]
`UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.`

I think this is still the main problem. SmartThings is telling us it can't find the Door device type in your IDE setup. I'm not sure why that is, but if it can't find the door type, it won't create a Thing for you to interact with. Maybe get me a screenshot of the device type in your IDE like the one below?


![image](https://user-images.githubusercontent.com/7239272/32281666-84a9eed4-beed-11e7-8d17-f9ea10fd2d43.png)

**Comment by bishopmax** [comment]
Looks like I don’t have everything added so that may be the issue.  I also can’t delete that “old” one.

**Comment by bishopmax** [comment]
I tried adding the other ones and get:

 



 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 5:31 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

Looks like I don’t have everything added so that may be the issue.  I also can’t delete that “old” one.

**Comment by bishopmax** [comment]
I was able to clean up and get rid of all the myq smart apps thinking that was the problem.  I still get that error when trying to create a new smartapp.

 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 5:37 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

I tried adding the other ones and get:

 



 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 5:31 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com <mailto:SmartThings_MyQ@noreply.github.com> >
Cc: 'Author' <author@noreply.github.com <mailto:author@noreply.github.com> >
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

Looks like I don’t have everything added so that may be the issue.  I also can’t delete that “old” one.

**Comment by bishopmax** [comment]
Any chance you were able to look at that error I am getting when trying to save the code to publish for myself?

 

Thanks,

Paul

 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 8:30 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

I was able to clean up and get rid of all the myq smart apps thinking that was the problem.  I still get that error when trying to create a new smartapp.

 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 5:37 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com <mailto:SmartThings_MyQ@noreply.github.com> >
Cc: 'Author' <author@noreply.github.com <mailto:author@noreply.github.com> >
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

I tried adding the other ones and get:

 



 

From: PRP [mailto:f.hugh@comcast.net] 
Sent: Wednesday, November 1, 2017 5:31 PM
To: 'brbeaird/SmartThings_MyQ' <reply@reply.github.com>; 'brbeaird/SmartThings_MyQ' <SmartThings_MyQ@noreply.github.com <mailto:SmartThings_MyQ@noreply.github.com> >
Cc: 'Author' <author@noreply.github.com <mailto:author@noreply.github.com> >
Subject: RE: [brbeaird/SmartThings_MyQ] Stopped working and now can't add it back. (#19)

 

Looks like I don’t have everything added so that may be the issue.  I also can’t delete that “old” one.

**Comment by bishopmax** [comment]
I tried to add it again after remove all the myq stuff on my account.  When I try to create them again. I get the following error and I am just copying the raw code into the smartthings create smartapp interface.

![image](https://user-images.githubusercontent.com/33165895/32554712-52423730-c460-11e7-8893-910423e56676.png)

**Comment by brbeaird** [comment]
According to that screenshot, you are pasting the device handler code into a new SmartApp. The MyQ Lite SmartApp code needs to go in there.

**Comment by bishopmax** [comment]
For crying out loud, what a dummy.  I guess it has been awhile since I have done this.  I will load them up and see how it works.  Thanks.

**Comment by bishopmax** [comment]
I was able to load things up fine and can open and close the garage door now.  Thanks for helping out.  Now I just need to figure out why my goodbye and welcome activity aren't closing the door.  That isn't your  issue.  Again Thanks for all the help!

**Comment by brbeaird** [comment]
Nice! Glad you got it going.
