### ISSUE TITLE
No sure what happened

### ISSUE THREAD

**Issue by monthrope** [brbeaird/SmartThings_MyQ#21]
All was well, then at some point while the craftsman garage opener was still visible.  Click open, no action, click close, no action at the door.  
I then removed the device thinking i would rebuild / install everything,  This may have made  things worse, but now I get an error when i attempt to login via the MyQ Lite / SmartApps within ST -  indicating "Could not find any supported device(s).  Please report to author about these devices - any thoughts?

**Comment by brbeaird** [comment]
Have you updated to the last SmartApp code? I put in a fix awhile ago for the scenario you described.

**Comment by RedsGT** [comment]
I'm seeing the same thing, and I've made sure i have the latest from the repro.

**Comment by RedsGT** [comment]
c47f18df-ad70-4c6f-8f12-beb97fb2d8ae  6:31:41 PM: debug got login response: groovyx.net.http.HttpResponseDecorator@6ebeb4f5

Not much for logs when this happens.

**Comment by RedsGT** [comment]
Enabled the debug line 613:

	apiGet("/api/v4/userdevicedetails/get", []) { response ->
		if (response.status == 200) {

c47f18df-ad70-4c6f-8f12-beb97fb2d8ae 6:54:41 PM: debug response data: null

That's not good...

**Comment by RedsGT** [comment]
apiGet("/api/v4/userdevicedetails/get", []) { response ->
		if (response.status == 200) {
        log.debug "response data1: " + response
        log.debug "response data2: " + response.data
        log.debug "response data3: " + response.data.Devices

7:14:38 PM: debug response data3: null
7:14:38 PM: debug response data2: [CorrelationId:9a7e571a-529e-475b-8978-9e0d2ebc8be9, ReturnCode:216, ErrorMessage:Unauthorized (216)]
 7:14:38 PM: debug response data1: groovyx.net.http.HttpResponseDecorator@3735b499

I've verified that my password is good and I'm thinking we shouldn't be getting this far if unauthed.

**Comment by brbeaird** [comment]
If you want to set your account username/password to something temporary I can use to login and see how MyQ is responding, let me know, and I'll send you my e-mail.

**Comment by RedsGT** [comment]
I'm in.  Drop me a line.

**Comment by brbeaird** [comment]
Send me a note - brbeaird@gmail.com

**Comment by jrsprice** [comment]
I've experienced the same thing. Door will not close. With the garage opener if I hit "open" again it will close. On actiontiles, all devices - momentary, garage opener, and the on/off switch will not close the door.

**Comment by RedsGT** [comment]
I worked with @brbeaird on my issue off line and it turned out that SmartThing IDE wasn't updating the code from GitHub so I wasn't getting the latest updates.  Wiping it out completely and then pulling it down again fixed my issue.

**Comment by jrsprice** [comment]
Thanks @RedsGT, I only had pulled from github for the updates. I might have to remove and install again. I had the same issue when both didn't work. With the updated code (from pull) it seems only the open CTA will do both open and close my garage. Can't close it with the close CTA.

**Comment by jrsprice** [comment]
@brbeaird If I flip the bit from 0 to 1 in the close function of the garage door opener device handler it works now. I'm using the recommended tilt sensor too. I'll have to debug log some more.

```groovy
def close() { 
	log.debug "Garage door close command called."
    parent.notify("Garage door close command called.")
	parent.sendCommand(this, "desireddoorstate", 1) 
//	updateDeviceStatus("closing")			// Now handled in the parent (in case we have an Acceleration sensor, we can handle "waiting" state)
    runIn(30, refresh, [overwrite: true]) //Force a sync with tilt sensor after 30 seconds
}
```

**Comment by jrsprice** [comment]
@RedsGT and @brbeaird as well as whoever finds this. The problem I encountered is due to the MyQ tilt sensor. The battery was dead and Chamberlain's product doesn't provide that information on their app. All the other smart devices usually report the charge %. Reason the MyQ app says my garage has been closed for 2 months. No wonder why the caution beep and blinking light didn't turn on when closing - AKA the liability prevention which completely fails when that battery dies. To top it off, it uses a CR2450 3V cell where as most other smart devices I have use CR123A/RCR123A (rechargeable cells) that all show 100%. Even my Kwikset locks show 60% on 4 rechargeable AA.

Anyway, for a temporary solution - flipping that bit works :)

**Comment by brbeaird** [comment]
> The battery was dead and Chamberlain's product doesn't provide that information on their app. All the other smart devices usually report the charge %. Reason the MyQ app says my garage has been closed for 2 months. No wonder why the caution beep and blinking light didn't turn on when closing

That is bonkers. Glad you got it figured out.
