### ISSUE TITLE
when I try to created new device handler it gives me an error

### ISSUE THREAD

**Issue by dkrastes** [brbeaird/SmartThings_MyQ#22]
Org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: script_dth_metadata_9f3c9280_150f_4f51_877b_924bb13cd638: 219: expecting '}', found '' @ line 219, column 16. return "2.1.1" ^ 1 error

**Comment by brbeaird** [comment]
Make sure you are:

1. Pasting in the raw code from GitHub - click the "raw" button
2. Pasting the device handler code, not the SmartApp code.

**Comment by dkrastes** [comment]
when I tried again it worked thanks this is awesome!
