### ISSUE TITLE
Support for MyQ Home Bridge

### ISSUE THREAD

**Issue by ThomasTrain** [brbeaird/SmartThings_MyQ#23]
I've been previously using the Craftsman MyQ gateway without issue with this smartapp.  I recently acquired a Chamberlain MyQ Home Bridge that has been successfully installed and setup in the MyQ Chamberlain app and operate properly.  However, upon trying to add this in the smartthings app I get an error "Error!  Could not find any supported device(s).  Please report to the author about these devices.

Let me know how I can help get this new MyQ Home Bridge supported.

**Comment by brbeaird** [comment]
Some people have seen this and been able to fix it by going into the MyQ app and renaming the door to something else and then trying again. If that still doesn't work, I can work with you via e-mail or some other DM channel to test out your account just so I can see exactly what the MyQ API is showing for your setup. Totally up to you, though.

**Comment by ThomasTrain** [comment]
You sir are a genius!  I would have never thought to try changing the name from the default.  Works perfectly now. Thank you.

**Comment by brbeaird** [comment]
Sweet! Honestly, I just sort of stumbled into that solution awhile back, but it has worked for quite a few people now. Glad it's working for you now.
