### ISSUE TITLE
Error Saving Unnamed Page

### ISSUE THREAD

**Issue by jsmith0103** [brbeaird/SmartThings_MyQ#24]
Had been using the app for a while, but one of the doors was stuck in “opening” mode. I figured I’d just delete it and re-add it, but when I get to the final stage to add the door I recieve an error that says “Error saving unnamed page. Please contact the SmartApp developer.”

Any ideas?

**Comment by brbeaird** [comment]
Someone reported this same thing in the ST community thread. Have you tried just updating your SmartApp code to the most recent version? It fixes something that has been gradually breaking the integration for people as Chamberlain makes changes on their side.

If you're getting errors trying to delete it, could you try that with live logging open to try and figure out what's preventing the app from uninstalling?

**Comment by jsmith0103** [comment]
Deleting the entire app out of the SmartThings App seemed to fix it, but then another curious issue...when reinstalling the garage doors I get a warning that there is a more current version of the app, however when logging into the SmartThings website I don't see any GitHub updates, and my code *looks* to be the most current version (released 10/28/2017) - any ideas there?

Also, thank you for putting this out and supporting it - I've found it to be extremely useful!

**Comment by brbeaird** [comment]
Gah, you're right. I didn't properly update the metadata correctly. I just pushed another commit that should fix that. The latest version of the SmartApp is 2.0.3, last updated 11/28.

**Comment by jsmith0103** [comment]
Great - thank you again for your help!
