### ISSUE TITLE
Smartthings MyQ Lite no supported devices

### ISSUE THREAD

**Issue by rchoughton** [brbeaird/SmartThings_MyQ#26]
I had all this working until a few weeks ago.  I went into my SmartThings IDE today to take a look at it and I was missing the device handlers and smart apps. I added those back in and then went to my SmartThings SmartAppsAs I go though the steps I get the error "Could not find any supported device(s). ..." 
Any idea what I need to do to resolve?

**Comment by brbeaird** [comment]
When people have seen that lately, it's been because they didn't have the absolute latest SmartApp code version. Are you sure you've got the latest one published?

**Comment by rchoughton** [comment]
Thank you for getting back to me. I bet you are correct. I have tried to delete the current smart app to install the new one and I keep getting a message that an error has occurred. 
I have tried to just go and add it again, but nothing changes in the issue. 
Any recommendations from here?
I do appreciate your help.

**Comment by brbeaird** [comment]
That error normally happens if the door created by the SmartApp is still in
use by another routine/SmartApp/etc. I would suggest going to the door in
the mobile app and clicking the SmartApps tab to see where it may still be
in use. You could also check the IDE logs while you try to remove it and
see if you get a more detailed message.

**Comment by sumguyatvt** [comment]
I used ST Community Installer to install MyQ. How do I update?

**Comment by brbeaird** [comment]
I believe if you go back into the Community Installer, there's an option to update if newer code is out there.

**Comment by sumguyatvt** [comment]
You are great - thanks boss!
