### ISSUE TITLE
New Install, No Devices Found

### ISSUE THREAD

**Issue by hcc-union** [brbeaird/SmartThings_MyQ#27]
I have two commercial openers that the SmartApp cannot find. Is there a difference between the commercial and residential? Thanks!

**Comment by hcc-union** [comment]
"Could not find any supported device(s). Please report to author about these devices: [9|null, 9|null]

**Comment by hcc-union** [comment]
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug found device: Building 3A West
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug MyQDeviceTypeId : 9
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug found device: Building 3A East
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug MyQDeviceTypeId : 9
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug MyQDeviceTypeId : 1
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:12 PM: debug got login response: groovyx.net.http.HttpResponseDecorator@4d1d9baa
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug lightVersion: 1.0.1
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug doorNoSensorVersion: 1.1.1
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug doorVersion: 2.1.2
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug latestVersion: 2.0.3
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug installedVersion: 2.0.3
ea3d3bb2-e64d-41fd-90fd-da2bb7fe9884  12:35:11 PM: debug previousVersion: 0
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug lightVersion: 1.0.1
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug doorNoSensorVersion: 1.1.1
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug doorVersion: 2.1.2
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug latestVersion: 2.0.3
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug installedVersion: 2.0.3
5aad9cda-9c5f-47c6-86c7-95677e433020  12:35:00 PM: debug previousVersion: 0

**Comment by hcc-union** [comment]
![myq](https://user-images.githubusercontent.com/35668302/35198705-c428685c-fea7-11e7-92ac-e104989271e2.PNG)

**Comment by brbeaird** [comment]
Hmm. I've never tried with a commercial version, but I would imagine it would work the same. If this is the first time you've installed, could you try renaming the doors in the native MyQ app to something slightly different and trying again? For some reason that works sometimes. If it doesn't, you can e-mail me directly, and I could take a look at exactly what the API looks like for you account.

**Comment by hcc-union** [comment]
Thanks Brian, I named them different, however same result.

Thanks!

Spencer Jones
Hood Canal Communications
sjones@hcc.net<mailto:sjones@hcc.net>
360-898-2481
“Keeping Our Community Connected”

The information in this e-mail message is privileged and confidential.  It is intended only for the use of the recipients named above.  If you received this transmission in error, you are hereby notified  that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this message in error, please do not read it.  Please reply to sender and delete this mail.  Thank you.

**Comment by brbeaird** [comment]
If you're willing, send me a login and temp password to brbeaird@gmail.com, and I'll take a look at the API response (I won't actually send any commands).

**Comment by hcc-union** [comment]
Thanks Brian, are you talking about the Samsung API portal?

Thanks!

Spencer Jones
Hood Canal Communications
sjones@hcc.net<mailto:sjones@hcc.net>
360-898-2481
“Keeping Our Community Connected”

The information in this e-mail message is privileged and confidential.  It is intended only for the use of the recipients named above.  If you received this transmission in error, you are hereby notified  that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this message in error, please do not read it.  Please reply to sender and delete this mail.  Thank you.

**Comment by brbeaird** [comment]
No, this would be your MyQ account. I'll just do a login and device list call manually through the MyQ API to see what data comes back and see why the SmartApp isn't picking up the doors.

**Comment by hcc-union** [comment]
Gotcha, thanks Brian, ill send it over shortly

Spencer Jones
Hood Canal Communications
sjones@hcc.net<mailto:sjones@hcc.net>
360-898-2481
“Keeping Our Community Connected”

The information in this e-mail message is privileged and confidential.  It is intended only for the use of the recipients named above.  If you received this transmission in error, you are hereby notified  that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this message in error, please do not read it.  Please reply to sender and delete this mail.  Thank you.

**Comment by brbeaird** [comment]
Turns out the corporate doors have a slightly different ID. I added handing to this in the latest commit.
