### ISSUE TITLE
You don't have access to brbeaird/SmartThings_MyQ

### ISSUE THREAD

**Issue by rchoughton** [brbeaird/SmartThings_MyQ#29]
When I try to the myq as a repository, I get the error message "You don't have access to brbeaird/SmartThings_MyQ".  Any ideas what I need to look at to fix?

**Comment by mgguirguis** [comment]
Search for the original repo. It will have step by step instructions.

**Comment by brbeaird** [comment]
You're trying to add it as a repo in the SmartThings IDE? It should look like this:

![image](https://user-images.githubusercontent.com/7239272/40059928-f778fccc-581a-11e8-8c4a-26b7f6980a46.png)

**Comment by rchoughton** [comment]
that is exactly what I am doing.

**Comment by brbeaird** [comment]
If that doesn't work, something may be up with your github-SmartThings integration in general. You might try disconnecting the github integration and starting over? Not quite sure what would cause that.

**Comment by mgguirguis** [comment]
I did not make the files originally. You have to find the original one.
Search on Google or in the search area for it. Search myQ or brbeaird

**Comment by RandomEngy** [comment]
Disconnecting github integration and reconnecting worked for me.
