### ISSUE TITLE
Can't Add Device Hanlder

### ISSUE THREAD

**Issue by RogueSolo** [brbeaird/SmartThings_MyQ#30]
Hi, 
I'm trying to add the no sensor device app.  I've tried to do it manually and from GitHub directly and I'm getting errors with both approaches.  When I do it manually I get this error:

Org.springframework.dao.InvalidDataAccessResourceUsageException: could not load an entity: [physicalgraph.device.Capability#172]; SQL [select capability0_.id as id78_0_, capability0_.version as version78_0_, capability0_.canonical_id as canonical3_78_0_, capability0_.canonical_version as canonical4_78_0_, capability0_.date_created as date5_78_0_, capability0_.display_name as display6_78_0_, capability0_.in_store as in7_78_0_, capability0_.last_updated as last8_78_0_, capability0_.name as name78_0_ from capability capability0_ where capability0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not load an entity: [physicalgraph.device.Capability#172]

When I attempt to add it via GitHub I get this error:

**Error**  500: Internal Server Error
**URI**  /ide/device/doRepoUpdates
**Reference Id**  a046373b-b31a-4994-9a08-98e485c0e67e
**Date**  Wed May 16 17:33:36 UTC 2018

I dont believe I'm doing anything wrong.  Do these scripts still work 'as is', or is an update required?  If they are still working for other people then any idea what I need to do differently?

I should also note that I was able to add the new SmartApp with no issues.  The error is just for the device handler(s).  The error above is for the Door No Sensor one, but I have tried all of them and get the same error.  

Thanks

**Comment by brbeaird** [comment]
I've not seen that error before. Have you tried again since then? You should be able to copy/paste the code straight into a new device handler code page to create the handler.

**Comment by RogueSolo** [comment]
I tried this again a few days later and the error no longer occurred.  
Seems to be working now.  Thanks
