### ISSUE TITLE
Error saving unnamed page. Please contact SmartApp developer.

### ISSUE THREAD

**Issue by pilot76103** [brbeaird/SmartThings_MyQ#31]
I am attempting to add the MyQ Lite app using SmartThings Classic 2.16 on iOS. It allows me to authenticate with my Craftsman branded GDO, select the GDO, then configure sensors and seperate buttons but after clicking next I am presented a page that is blank with a "Done" button. When clicking "Done" I get an error in a red banner stating "Error saving unnamed page. Please contact SmartApp developer.". I have installed and published all device handlers and the SmartApp from this GitHub. Does this SmartApp require a SmartThings hub unlike NST Manager (Nest Manager) because that is one item I do not have.

**Comment by brbeaird** [comment]
Yes, this was written assuming you've got a SmartThings hub. However, it is possible to make it work if you  manually edit the code to send null instead of getHubID().

**Comment by brbeaird** [comment]
I just made a small update that I think should actually fix this in case you don't have a hub. Feel free to pull down the newest SmartApp code and give that a shot.

**Comment by pilot76103** [comment]
@brbeaird that was the quickest I have ever had an issue like that resolved. I will test when I get home however the initial complaint of not being able to add the GDO is resolved.
