### ISSUE TITLE
Could Not Find Any Supported Device(s)

### ISSUE THREAD

**Issue by lgbro451** [brbeaird/SmartThings_MyQ#32]
I saw that this was a previous issue that was closed, but no solution listed has solved my issue.  I've deleted all device handlers and the smartapp and readded them all to no avail.  I would greatly appreciate some insight as to where I can look to next for some troubleshooting.

I'm not quite sure if I'm using the most current smartapp code but I am using the links provided in the readme on the main code page.  I'm new to GitHub but have enough technical experience to figure this out if someone can lead me in the right direction!  Thanks in advance!

**Comment by brbeaird** [comment]
No worries. The latest SmartApp code is here: https://raw.githubusercontent.com/brbeaird/SmartThings_MyQ/master/smartapps/brbeaird/myq-lite.src/myq-lite.groovy

Totally removing everything and then pasting in that code is the best bet for fixing this.

If you're still not seeing any supported devices and want further investigating, I can look into your account with a temporary password, but I'll leave that up to you.

**Comment by lgbro451** [comment]
Thanks for the quick reply.

The code at your link is what I have already but I removed existing code, pasted from your link, and I still get the same result.  I'm in for having you take a look, that'd be great.  I can PM you my changed password if that works.

How can I donate?

**Comment by brbeaird** [comment]
Shoot me an e-mail at brbeaird@gmail.com, and I'll take a look at what the MyQ API is showing for you account.

Donations are certainly appreciated :-)  Link for that here: https://www.paypal.com/donate/?token=MVgfLDwGxQm8xs61n8Kj6iav8AcZ9zVUBgFEarTyBqeVyoXO0c47g54xZVCjP5p8pv18tG&country.x=US&locale.x=US

**Comment by adrian97c** [comment]
Love the support, I will soon have a craftsman sears brand (made by chamberlain)WiFi opener installed & was told by another craftsman user that this app makes it ST & Alexa compatible! I will donate once I confirm it works for me as well.

**Comment by pepper39992016** [comment]
Were you able to find a code that worked for integrating this?

**Comment by brbeaird** [comment]
I was able to get this fixed with @lgbro451 - turns out his SmartThings IDE had stuff out of sync across multiple SmartThings cloud shards, so even though he updated the code on one shard, it was still using the older version on the main shard used by the mobile app. Once we got it updated in both places, things were good to go.
