### ISSUE TITLE
MyQ Lite is not working

### ISSUE THREAD

**Issue by gregmora** [brbeaird/SmartThings_MyQ#34]
Hi,

I ran all the procedures and I I don't get any errors, but if I execute the command, it doesn't open or closes the door.

Thanks,

Jose

**Comment by brbeaird** [comment]
From the SmartThings IDE in a browser, can you open up live logging and then try to open or close the door and see what the logs say?

**Comment by gregmora** [comment]
Hi,

I ran the simulator and this is the log:
fce4eade-1764-4b50-a563-958f60ea5044 9:57:53 AM: debug Door: Garage Door Opener: Updating timestamp to: Fri Aug 10 13:57:53 UTC 2018 - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:57:53 AM: debug Door: Garage Door Opener: Updating with status - open - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:57:53 AM: debug Sensor change detected: Event name contact value: open deviceID: 98a21732-ab24-4bd0-bae7-662c3d228887
fce4eade-1764-4b50-a563-958f60ea5044 9:57:35 AM: debug Updated...
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Door: Garage Door Opener: Updating with status - null - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug ID's to look for: [4 Opener, 4 Closer]
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating child door device e
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug ID's to look for: [c Opener, c Closer]
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating door with no sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Child already exists for Garage Door Opener. Sensor name is: door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Found door: 1703372993
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: error java.lang.NullPointerException: Cannot get property 'name' on null object @line 470 (updateDoorStatus)
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Door: Garage Door Opener: Null timestamp detected - from sensor door1Sensor . Keeping current value.
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating door with no sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Error! physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating child door device 4
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug ID's to look for: [e Opener, e Closer]
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Error! physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating door with no sensor
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Error! physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Creating child door device c
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug ID's to look for: [fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993 Opener, fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993 Closer]
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Storing door info: Garage Door Openertype: 7 status: 2 type: VGDO
fce4eade-1764-4b50-a563-958f60ea5044 9:55:42 AM: debug Initializing...
fce4eade-1764-4b50-a563-958f60ea5044 9:55:38 AM: debug Single door detected (string).
fce4eade-1764-4b50-a563-958f60ea5044 9:55:38 AM: debug Doors chosen: fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993
fce4eade-1764-4b50-a563-958f60ea5044 9:55:31 AM: debug Storing door info: Garage Door Openertype: 7 status: 2 type: VGDO
fce4eade-1764-4b50-a563-958f60ea5044 9:55:31 AM: debug Found door: 1703372993
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug got login response: groovyx.net.http.HttpResponseDecorator@516f9e9c
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug lightVersion: 1.0.1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug doorNoSensorVersion: 1.1.1
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug doorVersion: 2.1.2
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug latestVersion: 2.0.3
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug installedVersion: 2.0.3
fce4eade-1764-4b50-a563-958f60ea5044 9:55:30 AM: debug previousVersion: 2.0.3

**Comment by gregmora** [comment]
![screen shot 2018-08-10 at 9 58 51 am](https://user-images.githubusercontent.com/42253077/43961963-5e821680-9c84-11e8-8ade-9ddbaa0a167e.jpg)

**Comment by brbeaird** [comment]
Ok, that error indicates you're missing the device handler (or you haven't
gone in and clicked "publish" on it in the IDE). Can you check your device
handlers there and make sure you've got the no-sensor door handler
published?

**Comment by gregmora** [comment]
Ok.. I think we got a bit farther, I get no errors, but it doesn't open or closes the garage.

fce4eade-1764-4b50-a563-958f60ea5044 10:54:05 AM: debug Door: Garage Door Opener: Updating timestamp to: Fri Aug 10 14:54:05 UTC 2018 - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 10:54:05 AM: debug Door: Garage Door Opener: Updating with status - open - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 10:54:05 AM: debug Sensor change detected: Event name contact value: open deviceID: 98a21732-ab24-4bd0-bae7-662c3d228887
fce4eade-1764-4b50-a563-958f60ea5044 10:53:52 AM: debug Door: Garage Door Opener: Updating timestamp to: Fri Aug 10 14:53:52 UTC 2018 - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 10:53:52 AM: debug Door: Garage Door Opener: Updating with status - closed - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 10:53:52 AM: debug Sensor change detected: Event name contact value: closed deviceID: 98a21732-ab24-4bd0-bae7-662c3d228887
fce4eade-1764-4b50-a563-958f60ea5044 10:53:14 AM: debug Updated...
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Door: Garage Door Opener: Updating timestamp to: Fri Aug 10 13:57:53 UTC 2018 - from sensor door1Sensor
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Creating child door device 4
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug getChildDevices(false), children=1
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Error! physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Creating child door device e
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug ID's to look for: [c Opener, c Closer]
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Error! physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found.
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Creating child door device c
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug button devices to delete: []
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug ID's to look for: [fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993 Opener, fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993 Closer]
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug In CreateChild
fce4eade-1764-4b50-a563-958f60ea5044 10:53:03 AM: debug Found door: 1703372993
fce4eade-1764-4b50-a563-958f60ea5044 10:52:50 AM: debug Single door detected (string).
fce4eade-1764-4b50-a563-958f60ea5044 10:52:50 AM: debug Doors chosen: fce4eade-1764-4b50-a563-958f60ea5044|GarageDoorOpener|1703372993
fce4eade-1764-4b50-a563-958f60ea5044 10:52:38 AM: debug Storing door info: Garage Door Openertype: 7 status: 2 type: VGDO
fce4eade-1764-4b50-a563-958f60ea5044 10:52:38 AM: debug Found door: 1703372993
fce4eade-1764-4b50-a563-958f60ea5044 10:52:37 AM: debug got login response: groovyx.net.http.HttpResponseDecorator@119bb143
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug lightVersion: 1.0.1
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug doorNoSensorVersion: 1.1.1
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug doorVersion: 2.1.2
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug latestVersion: 2.0.3
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug installedVersion: 2.0.3
fce4eade-1764-4b50-a563-958f60ea5044 10:52:36 AM: debug previousVersion: 2.0.3

**Comment by brbeaird** [comment]
If you're working in the simulator, I'm honestly not sure that will fully work. When you try to open it from the mobile app, we should see some sort of "opening" message on the live logging.

**Comment by gregmora** [comment]
It worked!!! Thanks!!!

**Comment by brbeaird** [comment]
Awesome! Glad to hear it.

**Comment by tylercoop** [comment]
Installed both the SmartApp and Device Handler via the GitHub integration.  This seemed to work perfectly, and both show up as published in the IDE.  When I try to add the app within the ST mobile app, it doesn't show up under My Apps (only my Konnected app shows up for my integrated alarm panel).  Has anyone experienced this before?

Thanks.

**Comment by brbeaird** [comment]
@tylercoop  - you may need to check and make sure your IDE and mobile app aren't pulling from different shards. What's the URL when you're logged into the IDE where you've installed the SmartApp? Sometimes you'll get bounced to "naX.." instead of just "graph.api..."

**Comment by tylercoop** [comment]
I was out of town, so unable to get this straightened out until now.  You were correct in your suspicion that my IDE and app were out of sync.  Everything is working flawlessly now.

 

Thank you for your help!
