### ISSUE TITLE
MyQ Lite issue

### ISSUE THREAD

**Issue by jpacione** [brbeaird/SmartThings_MyQ#35]
i am using this, with a door sensor.  Sensor is reporting accurately, but can’t get the door to open or close.  Here is the log:

4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: debug Door: Main Garage Door Opener: Updating timestamp to: Tue Aug 14 00:54:17 UTC 2018 - from sensor Main Door Tilt Sensor
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: debug Door: Main Garage Door Opener: Updating with status - closed - from sensor Main Door Tilt Sensor
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: debug refresh called from Main Garage Door Opener (1485502d-e5d8-410d-88fe-bd7cc44fed2c|GarageDoorOpener|1703322266)
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: error java.lang.NullPointerException @line 202 (updateDeviceLastActivity)
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: debug Door is now closed
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:35 PM: debug Request received to update door status to : closed
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:15 PM: debug Request received to update door status to : opening
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:15 PM: debug Garage door open command called.
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:05 PM: debug Door is already closed. Leaving status alone.
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:05 PM: debug Request received to update door status to : closing
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:05 PM: debug Garage door close command called.
4eb108a7-6e82-456b-924e-e435a84bc1eb  8:45:05 PM: debug Garage door close command called

**Comment by brbeaird** [comment]
Odd. Seems like the tilt sensor has some kind of unexpected value. Is it still doing this for you?

**Comment by jpacione** [comment]
Yes, it is.  Latest log...

![ad8dc4c2-4c86-4b67-9a78-d728d2850757](https://user-images.githubusercontent.com/10892123/44759121-c7c7ad80-aafd-11e8-866b-3a0cd78fee0f.png)

**Comment by jpacione** [comment]
The tilt sensor is an eco link Z-wave Plus Gold Plated Reliability Garage Door Tilt Sensor, White (TILT-ZWAVE2.5-ECO)

**Comment by brbeaird** [comment]
Has this ever worked for you? That update status error is odd, but it shouldn't prevent the door opening or closing. Are you sure you've got the latest version of the SmartApp and device handler?

**Comment by jpacione** [comment]
It has not.  I bought the sensor because I saw your app and wanted to be able to do this.  I pulled the code maybe 4 weeks ago, and it didn’t work then.  Haven’t pulled it again.

**Comment by brbeaird** [comment]
Can you try going into the SmartApp and doing the setup without a sensor selected? I'd be curious to see the logs when you hit the open/close button on the no-sensor device type.

**Comment by jpacione** [comment]
Here it is:
![894ced9c-8e31-417d-a144-78df3ccb8556](https://user-images.githubusercontent.com/10892123/44861906-2fd1dd00-ac3f-11e8-89c0-6ef3716789f9.png)

**Comment by brbeaird** [comment]
That is so odd. I've never seen ST send an opening command and have it not work but not get an error from MyQ. I assume the door opens fine in the native MyQ app? Some people have had success renaming the door in that MyQ app and then reinstalling this SmartApp.

Could you also try changing your URL to graph.api.smartthings.com? And make sure the SmartApp version is the same? Sometimes the "shards" get out of sync where you end up with different versions of code across various SmartThings servers.

**Comment by jpacione** [comment]
Yep will try when I get home tonight or over the weekend.

**Comment by brbeaird** [comment]
Any luck on this? You ever get it working?
