### ISSUE TITLE
Issue with installing SmartApp

### ISSUE THREAD

**Issue by thambikutty** [brbeaird/SmartThings_MyQ#37]
I have a MyQ garage opener with a sensor stuck to my garage door. Initially, I installed the "no-sensor" device handler, not realizing I have a sensor. I was able to install the SmartApp on ST app. Then, I went back and deleted the SmartApp and device handler to install the one for "with sensor". When I tried to install the SmartApp on my ST app, it gave me this error message: Home: problem creating door device (no-sensor type). Check your IDE to make sure...

I am confused why it's saying "door device (no-sensor type)", when there is a MyQ sensor attached to the garage door. Any ideas?

**Comment by adrian97c** [comment]
You need a ST sensor

**Comment by thambikutty** [comment]
Ahh okay! Thanks!
