### ISSUE TITLE
Out of date URL in manual instructions

### ISSUE THREAD

**Issue by danielgoepp** [brbeaird/SmartThings_MyQ#38]
I recently had some issues trying this out, because I was going to the wrong place using the URL provided in these instructions. I posted a comment about this in the community:

https://community.smartthings.com/t/what-is-the-difference-between-the-ide-url-and-account-url/135364

And immediately got a response explaining what I was seeing:

https://community.smartthings.com/t/faq-how-to-find-out-what-shard-cloud-slice-ide-url-your-account-location-is-on/53923

Please update the URL in step one of the manual install instructions (Log in to the SmartThings IDE. If you don't have a login yet, create one.) from:

https://graph.api.smartthings.com/ide/
to
https://account.smartthings.com

**Comment by brbeaird** [comment]
Good catch, thanks.

Fixed in commit https://github.com/brbeaird/SmartThings_MyQ/commit/dcc2f2b7943dc87fe2abbbe7b20c842c5ccee376
