### ISSUE TITLE
Get unexpected error occurred 

### ISSUE THREAD

**Issue by roadglide03** [brbeaird/SmartThings_MyQ#4]
After I install the smart app and device handlers, I login the gateway and states automating then I get unexpected error occurred and it doesn't complete.  I can use the Liftmaster app just fine any ideas on what I can look at?  BTY I have 3 garages and it see all three during the config.

**Comment by brbeaird** [comment]
Can you login to the SmartThings IDE and run Live Logging while you run through the smart app setup? That's the only way to get a detailed error to figure out what's happening.

**Comment by roadglide03** [comment]
49a5aff6-2f94-44ee-99ce-8dd1fb055521 <https://graph-na02-useast1.api.smartthings.com/ide/logs#49a5aff6-2f94-44ee-99ce-8dd1fb055521> 1:17:24 PM: trace getPhrases(), state.welcomeIssue = null
0a6d16cd-3d25-4a74-a757-648f576b9552 <https://graph-na02-useast1.api.smartthings.com/ide/logs#0a6d16cd-3d25-4a74-a757-648f576b9552> 1:17:05 PM: debug getChildDevices(false), children=1
3532e40e-5bcb-4bbe-b015-4306394da2a8 <https://graph-na02-useast1.api.smartthings.com/ide/logs#3532e40e-5bcb-4bbe-b015-4306394da2a8> 1:16:27 PM: debug Parsed 'zw device: 02, command: 9881, payload: 00 32 02 21 64 00 00 00 4C 01 2C 00 00 00 4C ' to ['name':'energy', 'value':0.076, 'unit':'kWh', 'isStateChange':false, 'displayed':false, 'linkText':'Garage Heater', 'descriptionText':Garage Heater energy is 0.076 kWh]
e637e2aa-e552-470d-b5da-63f5ddcf8934 <https://graph-na02-useast1.api.smartthings.com/ide/logs#e637e2aa-e552-470d-b5da-63f5ddcf8934> 1:16:24 PM: info SHM getInitialData 0.016 (00) incidents:00, locationId:0b7aa124-d03c-4598-8181-8dc9f272305b
e637e2aa-e552-470d-b5da-63f5ddcf8934 <https://graph-na02-useast1.api.smartthings.com/ide/logs#e637e2aa-e552-470d-b5da-63f5ddcf8934> 1:16:24 PM: debug summaryData: [[icon:indicator-dot-green, iconColor:#79b821, value:Everything OK, heroInfo:[heroStatus:ok, heroMessage:Everything OK]]] - [[icon:indicator-dot-green, heroInfo:[heroStatus:ok, heroMessage:Everything OK], value:Everything OK, iconColor:#79b821]]
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: error physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'MyQ Garage Door Opener-NoSensor' in namespace 'brbeaird' not found. @ line 310
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Creating child door device 218331ab-f347-4209-acaa-f1126d65a148|GarageDoorOpener|4183544
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Storing door info: Garage Door Opener 1type: 2 status: 2 type: GarageDoorOpener
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Found door: 4183544
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Storing door info: Garage Door Opener 2type: 2 status: 2 type: GarageDoorOpener
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Found door: 4183557
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Storing door info: Garage Door Opener 3type: 2 status: 2 type: GarageDoorOpener
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug Found door: 4183572
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:21 PM: debug got login response: groovyx.net.http.HttpResponseDecorator@d49f972
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:20 PM: debug Initializing...
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:20 PM: debug Updated...
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:20 PM: debug Single door detected (array).
218331ab-f347-4209-acaa-f1126d65a148 <https://graph-na02-useast1.api.smartthings.com/ide/logs#218331ab-f347-4209-acaa-f1126d65a148> 1:16:20 PM: debug Doors chosen: [218331ab-f347-4209-acaa-f1126d65a148|GarageDoorOpener|4183544]
49a5aff6-2f94-44ee-99ce-8dd1fb055521 <https://graph-na02-useast1.api.smartthings.com/ide/logs#49a5aff6-2f94-44ee-99ce-8dd1fb055521> 1:16:19 PM: trace getPhrases(), state.welcomeIssue = null
 <https://graph-na02-useast1.api.smartthings.com/ide/logs#> 1:15:30 PM: info Waiting on events...
 <https://graph-na02-useast1.api.smartthings.com/ide/logs#> 1:15:30 PM: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
 <https://graph-na02-useast1.api.smartthings.com/ide/logs#> 1:15:30 PM: info This console provides live logging of your SmartThings.

**Comment by roadglide03** [comment]
I see the issue let me change the script

**Comment by roadglide03** [comment]
It snot able to use lift master sensors?

**Comment by roadglide03** [comment]
Ok works now with the no sensor bummer I can’t use the lift master sensors.  thanks Andy

**Comment by brbeaird** [comment]
Yep, you're right. Unfortunately, the Liftmaster/Chamberlain sensors that come with the gateway won't work with SmartThings.
