### ISSUE TITLE
Adding support to new SmartThings app

### ISSUE THREAD

**Issue by vseven** [brbeaird/SmartThings_MyQ#40]
Couple things that can be added that isn't perfect but makes it at least work until official documentation comes down:

- Add some meta data to the DTH:  
`vid: "generic-contact-4", ocfdevicetype: "oic.d.garagedoor", mnmn: "SmartThings"`
- Add capability "Health Check"
- Add a checkInterval statement to the functions installed() and updated() (This is a guess based on other DTHs but it seems to work):  	
`sendEvent(name: "checkInterval", value: 4 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "cloud", scheme:"untracked"])`
- Add a ping command required by health check tha doesn't actually do anything other then make ST happy:  
```
def ping() {
    logDebug "ping()"	
    return []
}
```

**Comment by brbeaird** [comment]
Oh wow, that's excellent. I'll give that a try, thank you!

**Comment by brbeaird** [comment]
So does all that need to go into DTH or are the functions going into the SmartApp? Also, I'm not familiar with the syntax of that first meta data piece...got any similar examples I could check out?

**Comment by vseven** [comment]
All DTH.  Here is a example of updated metadata in a "standard" DTH:

https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/f64411dcd14d1a41e886a0feaddd530f675d3888/devicetypes/smartthings/smartpower-outlet.src/smartpower-outlet.groovy#L18

There is no true garage control I've found.....generic-contact-4 is the closest but like I said its not perfect (shows two switches...one for garage door and one for just door control) but it at least lets it work in the new app and doesn't seem to affect Classic.  If I remove the capability door control it does show correctly.

Health check is a guess that seems to work ok.  Its based on this for the structure (example is z-wave): https://community.smartthings.com/t/fibaro-open-close-sensor-health-check/140043/7 and then the syntax in the health check command in the stock EcoBee handler: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/f64411dcd14d1a41e886a0feaddd530f675d3888/devicetypes/smartthings/ecobee-thermostat.src/ecobee-thermostat.groovy#L142 but honestly I wouldn't add that part yet. 

I would start with just the meta data and removing door control and you'll get it to at least show up in the new app and work.  It will show "checking status" but clicking on it will show correctly.

Also the new app wont show the change....it holds the old dth.  So to see it you have to delete the evice and re-add.

**Comment by brbeaird** [comment]
Gotcha. That's annoying to have to delete and re-add...too lazy to deal with that at the moment, but I'll try at some point. Thanks again!

**Comment by vseven** [comment]
Yeah, I feel the same way especially since I then have to reauthorize ActionTiles for that device and update my panel since the "old" garage door is gone.  But adding just the meta data and removing the "door Control" capability will give you a working device in the new app:

![image](https://user-images.githubusercontent.com/999179/47725215-87d09400-dc2e-11e8-8045-3b22376caeda.png)

I haven't found a fix for the "Checking Status..." issue yet.  Most people say adding the vid will fix it but it doesn't.

**Comment by brbeaird** [comment]
Ok, yep - I added my door to my second hub just to test it, and it now shows up in the new app.  Progress! Hopefully we'll see changes soon-ish to make it a bit more streamlined.
