### ISSUE TITLE
MyQ Lite doesn't see my sensor on the garage door.

### ISSUE THREAD

**Issue by twilson0813** [brbeaird/SmartThings_MyQ#42]
I have the Chamberlin MyQ opener and the smart things hub but when i have it set up, it says i do not have a door sensor. I do have one.

**Comment by brbeaird** [comment]
It needs to be a separate SmartThings-compatible door sensor, typically z-wave or zigbee. The built-in Chamberlain door sensor will not work, unfortunately.

**Comment by zauggerr** [comment]
What door sensor do you recommend?

**Comment by brbeaird** [comment]
This one should be fine https://amazon.com/Z-Wave-Plated-Reliability-Garage-TILT-ZWAVE2-5-ECO/dp/B01MRZB0NT
