### ISSUE TITLE
MyQ Lite setup.  Issue in setup

### ISSUE THREAD

**Issue by zauggerr** [brbeaird/SmartThings_MyQ#43]
Hey, 

Upon adding MyQ app on Smarthings classic app.. Enter creds, it accepts, next page it lets me select my garage door (next). The next page comes up blank for me. Although if i simulate the app through the smarthings IDE i can see the page is supposed to ask me my sensor/contact preferences.  

Pulled most recent MyQ app and only using "MyQ Garage Door Opener" device handler.

**Comment by brbeaird** [comment]
Could you open live logging in the IDE while you do this? I'm sure it's related to the most recent change I made, but it would help to know exactly what line yours is blowing up on.

**Comment by brbeaird** [comment]
Actually, I think I see the problem. I just pushed an update to the SmartApp code. Give that a shot.

I think it had a bug in there that was happening for single-door setups.

**Comment by zauggerr** [comment]
Thanks! I'm able to get by that step now and select my contact sensor. 

One thing, i did have to change ' "state.thisSmartAppVersion = "2.0.5" ' to 2.0.6. 

Although now it successfully adds, says its saved. but doesnt list any additional devices under my home

**Comment by Devindao** [comment]
Im having the same problem. I thought I broke it. I was reinstalling the smartapp over and over, because the routine for myq is not working.

**Comment by brbeaird** [comment]
Yes - SmartThings routines won't work well if the door status is not known It is possible to work around this by using WebCORE instead, but it takes a few more steps.

**Comment by zauggerr** [comment]
Great! everything is working for me now.

Thanks for the quick response :)
