### ISSUE TITLE
Garage door does not show up in the app

### ISSUE THREAD

**Issue by Zhourj** [brbeaird/SmartThings_MyQ#44]
I just went through the setup process with no issues (except for the complains about app version 2.05 not 2.06). However, I cannot find the garage door anywhere in the app after setup. Did I miss anything?

**Comment by brbeaird** [comment]
What did the very last page in the setup say? It should tell you which things were created. Did you refresh the "things" page after install?

**Comment by Zhourj** [comment]
Thanks for the prompt reply. At the very last page, the summary says Your SmartApp version (2.0.5) is not the latest version (2.0.6). When i changed the version number in the smartapp to 2.0.6 in the code, the installation details will be blank.

**Comment by Zhourj** [comment]
I just fixed it by changing line  365 to  if (doors instanceof List).  For some reason, the doors variable in my case is a list not a string.. Now, i can add the garage door. However, it errored out when creating the push button. Will check what happened

**Comment by Zhourj** [comment]
Never mind. The push button actually worked. Thanks man, this is an awesome tool.
