### ISSUE TITLE
Unable to add to "things"

### ISSUE THREAD

**Issue by Chicagobrazil** [brbeaird/SmartThings_MyQ#45]
I have followed all the instructions on the read me and was not able to get this working properly.
I see it under "My Apps", went through the set up in there and still not able to get it working in anyway.

I was trying to get it set up with "No Sensor" as i just moved and most of my sensors are MIA

**Comment by Chicagobrazil** [comment]
I started with the  - No sensor - Code date 11/23
Added from your repository as well since i could not get the other to work
https://puu.sh/C6O4X.png

**Comment by Chicagobrazil** [comment]
Not sure what i did to fix it but it works now! Will be adding a switch once i can find where the box with 90% of my sensors are.
Thanks!

**Comment by brbeaird** [comment]
Great! Glad it's working now.
