### ISSUE TITLE
Can't finish app setup

### ISSUE THREAD

**Issue by cambuehl** [brbeaird/SmartThings_MyQ#50]
When I first setup the device handlers and smart app on my first hub, everything worked great.  I recently had to replace that hub with another v3 replacement and when I try to add the smart app to the new hub, the app gets stuck at the light controller.  I'm able to choose both garage doors then just a completely blank page.  Please let me know what info you'll need.  Thank you.

**Comment by brbeaird** [comment]
Try opening up the live logging in the IDE while running through setup and see what error you're getting.

**Comment by cambuehl** [comment]
Hello,

Thank you for the quick reply.  Here's a copy of the logs as I was running through the smart app setup again.  Please let me know if you need more info.  Thanks again for the help.

055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:47 PM: error org.springframework.security.access.AccessDeniedException: Access is denied @line 500 (createChilDevices)
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Creating door with sensor
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Creating child door device 055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777939
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug In CreateChild
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Found door: 1700777940
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Storing light info: Lighttype: 3 status: null type: LampModule
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Found light: 14117953
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Found door: 1700777939
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:46 PM: debug Initializing...
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:19 PM: debug 055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777939
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:19 PM: debug Multiple doors detected.
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:19 PM: debug Valid doors chosen: [055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777939, 055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777940]
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:19 PM: debug Doors chosen: [055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777939, 055cd2ec-ac45-4a93-9e84-a2102cf711ce|GarageDoorOpener|1700777940]
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Found door: 1700777940
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Storing light info: Lighttype: 3 status: null type: LampModule
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Found light: 14117953
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug Found door: 1700777939
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug got login response: groovyx.net.http.HttpResponseDecorator@7b253c34
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug lightVersion: 1.0.1
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug doorNoSensorVersion: 1.1.5
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug doorVersion: 2.1.7
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug latestVersion: 2.0.9
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug installedVersion: 2.0.9
055cd2ec-ac45-4a93-9e84-a2102cf711ce<https://graph-na04-useast2.api.smartthings.com/ide/logs#055cd2ec-ac45-4a93-9e84-a2102cf711ce> 2:09:02 PM: debug previousVersion: 0

________________________________

**Comment by brbeaird** [comment]
Access denied? That's a weird one. Have you tried again recently to see if maybe it was a temporary SmartThings glitch?

**Comment by cambuehl** [comment]
I've tried dozens of times in the 2 weeks since I setup this replacement hub.  Always with the same result, it just seems to freeze up on the light controller page after going through the garage door setup.

I am having a different issue with the new hub showing as offline on the classic app.  I'm trying to work that out with smartthings support, but to no avail yet.  All the devices show up when added, any changes are logged and show up in the app, yet is says my hub is offline.  Which has caused issues when trying to add devices with the classic app.  The connect app works fine with everything, it's just limited.

Not to get off topic, but I'm not sure if that smartthings issue could be contributing to what I'm experiencing with this smartapp.  I'm able to setup everything else in the smartapp, but it consistently stops with a blank screen at the light controller selection.


-------- Original message --------

**Comment by brbeaird** [comment]
I see your issue now. There is a bug in the light controller page. I assume you're adding a light but not selecting any doors? Working on a fix now.

**Comment by brbeaird** [comment]
I just pushed out another update. Could you try the newest SmartApp/DTH code and see if you can finish the setup now?

**Comment by cambuehl** [comment]
I just deleted and re-installed the device handlers and smartapp and I'm still running into the same problem.  I am adding two garage doors with sensors.  The smartapp sees both doors and the light controller,  then after selecting the sensors for the first then the second door it's the same blank page.  Let me know of you'd like me to send any more logs.  I appreciate the help.


-------- Original message --------

**Comment by brbeaird** [comment]
Could you post the IDE logs during setup once you hit the white screen?

**Comment by cambuehl** [comment]
Here's the latest logs when I try to get through the setup:

4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: error org.springframework.security.access.AccessDeniedException: Access is denied @line 573 (createChilDevices)
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Creating door with sensor
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Creating child door device 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug In CreateChild
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found door: 1700777940
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing light info: Lighttype: 3 status: null type: LampModule
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found light: 14117953
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found door: 1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Initializing...
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Multiple doors detected.
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Valid doors chosen: [4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939, 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777940]
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Doors chosen: [4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939, 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777940]
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug lightVersion: 1.0.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug doorNoSensorVersion: 1.1.6
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug doorVersion: 2.2.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug latestVersion: 2.1.2
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug installedVersion: 2.1.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug previousVersion: 0
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found door: 1700777940
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing light info: Lighttype: 3 status: null type: LampModule
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found light: 14117953
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found door: 1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:13 AM: debug got login response: groovyx.net.http.HttpResponseDecorator@ac58065

**Comment by cambuehl** [comment]
Here's the latest logs from when I try to get through the setup:

4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: error org.springframework.security.access.AccessDeniedException: Access is denied @line 573 (createChilDevices)
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Creating door with sensor
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Creating child door device 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug In CreateChild
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found door: 1700777940
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing light info: Lighttype: 3 status: null type: LampModule
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found light: 14117953
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Found door: 1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:54 AM: debug Initializing...
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Multiple doors detected.
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Valid doors chosen: [4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939, 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777940]
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:28 AM: debug Doors chosen: [4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777939, 4a64bda9-3e69-4843-b099-bbfbaa55ddae|GarageDoorOpener|1700777940]
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug lightVersion: 1.0.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug doorNoSensorVersion: 1.1.6
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug doorVersion: 2.2.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug latestVersion: 2.1.2
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug installedVersion: 2.1.1
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug previousVersion: 0
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing door info: Megan's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found door: 1700777940
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing light info: Lighttype: 3 status: null type: LampModule
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found light: 14117953
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Storing door info: Chris's Doortype: 7 status: 2 type: VGDO
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:14 AM: debug Found door: 1700777939
4a64bda9-3e69-4843-b099-bbfbaa55ddae  11:11:13 AM: debug got login response: groovyx.net.http.HttpResponseDecorator@ac58065

**Comment by brbeaird** [comment]
Something is odd with your setup. If you're cool with giving me temporary access to your MyQ account (not SmartThings) to try and debug it (no commands sending or anything like that), I'm glad to do that. Shoot me an e-mail with a MyQ username/Password at brbeaird@gmail.com.

**Comment by brbeaird** [comment]
Based on those logs, SmartThings is returning two hubs at your location, but apparently the first one is null. I just pushed another update to the SmartApp to try to more intelligently handle that. I'm still not totally sure it will work for you, but it might.

**Comment by cambuehl** [comment]
I'm guessing this stems from the issue that I'm having with the smartthings classic app thinking my hub is offline.  That issue started after replacing my first hub with the one I have now, and smartthings support is taking their time getting back to me after that ticket was sent up to the next tier of support.  I assumed that the issue with the ST classic app is because it's seeing 2 hubs for some reason.  Maybe their support will get back to me soon, I believe that issue is something they should be able to easily fix.

In the meantime I'll update the code for this smartapp and let you know the outcome.

Thanks for your time.


-------- Original message --------

**Comment by cambuehl** [comment]
That seems to have fixed it.  I was able to get through setup, all the devices including the light controller are listed and working.  Thanks for everything!


-------- Original message --------

**Comment by brbeaird** [comment]
Aweseome. Glad we got it fixed, and glad I was able to add in handling for it for anyone else who runs into it in the future.
