### ISSUE TITLE
no sensor version

### ISSUE THREAD

**Issue by jlkweb12** [brbeaird/SmartThings_MyQ#51]
I am getting an error adding the no-sensor version here.

 java.lang.NullPointerException: Cannot invoke method eventsSince() on null object @line 680 (updateDoorStatus)
debug Door: Garage Door: Updating with status - unknown - from sensor null
debug getChildDevices(false), children=1

**Comment by brbeaird** [comment]
This should be fixed now. Can you update and try again?
