### ISSUE TITLE
Couldn't connect to Garage Door. Try again later.

### ISSUE THREAD

**Issue by SireInsectus** [brbeaird/SmartThings_MyQ#52]
The command to open or close seems to work 1/3 tries. When it fails I get the error 
> Couldn't connect to Garage Door. Try again later

where "Garage Door" is the name of my door.

**Comment by brbeaird** [comment]
Where are you seeing this error exactly? This SmartApp does not generate that error message anywhere as far as I know.

**Comment by brbeaird** [comment]
Going to close this one for now - let me know if I can still help.
