### ISSUE TITLE
Add Door Status - API call in request.

### ISSUE THREAD

**Issue by krisrice** [brbeaird/SmartThings_MyQ#55]
From looking around the API. 

Add headers:
MyQApplicationId:  <appid>
SecurityToken: <securitytoken>

Door Status can be had from >
   /api/v4/deviceattribute/getdeviceattribute?MyQDeviceId=<DEVICEID>&AttributeName=doorstate

Sample Response where AttributeValue is the state
   {"AttributeValue":"2","UpdatedTime":"1548101307274","ReturnCode":"0","ErrorMessage":"","CorrelationId":"8d5afb41-447b-41c2-9159-24ad9f7bab5f"}

 doorStates: {
    1: 'open',
    2: 'closed',
    3: 'stopped in the middle',
    4: 'going up',
    5: 'going down',
    9: 'not closed',
  },

LightState can be had from > 
  /api/v4/deviceattribute/getdeviceattribute?MyQDeviceId=<DEVICEID>&AttributeName=lightstate

Sample Response where AttributeValue is the state
{"AttributeValue":"0","UpdatedTime":"1548101307274","ReturnCode":"0","ErrorMessage":"","CorrelationId":"74555d75-fc01-4df3-81a6-d1c90de25994"}

  lightStates: {
    0: 'off',
    1: 'on',

Constants from here >
   https://github.com/thomasmunduchira/myq-api/blob/master/src/constants.js

**Comment by brbeaird** [comment]
While technically possible, the reason we don't get door status is because MyQ and SmartThings have explicitly banned us from the polling that would be required to use this. See issue #41

**Comment by krisrice** [comment]
Interesting, considering MyQ charge for IFTTT integration they probably see it as lost money rather than a technical issue.
