### ISSUE TITLE
Love this work.... No Issue but quickest place I could say Thanks

### ISSUE THREAD

**Issue by john022662** [brbeaird/SmartThings_MyQ#56]
I donated $25 since I love this entire Automation. I even added the IFTTT for door sensors and that saved me much more than $25 and I never have to replace a battery.

Well Done.

If you have a way to Integrate Insteon Hub and Switches into SmartThings, would love to hear about it.

**Comment by brbeaird** [comment]
Thank you!! I really appreciate your generosity. Glad this app is serving
you well.

I haven’t messed with the Insteon stuff, but if I ever do, I’ll let you
know.
