### ISSUE TITLE
ST reports no devices found

### ISSUE THREAD

**Issue by Hyukishi** [brbeaird/SmartThings_MyQ#57]
Could not find any compatible devices when trying to add the smart app.  Below are my logged errors.

4cf6373e-d6cf-42a7-b634-3e7bcb756eb6 7:23:49 PM: debug API Error: java.net.SocketException: Connection reset
4cf6373e-d6cf-42a7-b634-3e7bcb756eb6 7:23:48 PM: debug API Error: java.net.SocketException: Connection reset
4cf6373e-d6cf-42a7-b634-3e7bcb756eb6 7:23:48 PM: debug got login response: groovyx.net.http.HttpResponseDecorator@3e52bb3d

**Comment by donfri** [comment]
+1

**Comment by brbeaird** [comment]
The good news: the door control API controls are still working, so existing automations seem ok (for now). 

Bonus good news: I can reproduce the issue within Postman on my computer, which means it's not a matter of MyQ blocking SmartThings connections.

The bad news: the initial "get device details" API call has changed somehow, which means the SmartApp setup is dead at the moment. Hopefully I can either figure it out or else someone with the ability to trace and reverse-engineer it (or from one of the other homebrew MyQ integrations) posts information about what has changed for that API call.

**Comment by guxdude** [comment]
Glad I found this. I just got a new lift master 8550 today and have been unable to find it using the myq lite smart app. I assume this is why? I believe I followed all the setup instructions properly.

**Comment by brbeaird** [comment]
Yep, that's why. I've been checking around several other code repositories that use this, and none of them have been updated yet. Maybe someone will find something later today.

**Comment by Hyukishi** [comment]
@brbeaird Is there a way to see what my security token is? I'm trying to debug on my end to help out however I can.

**Comment by brbeaird** [comment]
The token comes from making a POST call to /User/Validate. You could also edit the MyQLite SmartApp code on line 906 to this:

`log.debug "got login response: " + response.data.SecurityToken`

Then you'll see the token in your SmartThings live logs.

From what I've seen, these are the most likely things that may have changed on the device listing call:

- URL change (maybe even just a version number update)
- Call may have changed from GET to POST
- Headers may have changed
- If call is now POST, a request body may be needed

But unless I can get a hold of a device I can use to do some packet sniffing, it's anyone's guess what the change is.

**Comment by brbeaird** [comment]
Good news! I think I've got it working again. Just pushed an update.

Thankfully, the pymyq library (the one home assistance users) was not broken, so I was able to find the difference. Amazingly, it came down to something as simple as letter casing. I had to switch from this:

https://myqexternal.myqdevice.com/api/v4/userdevicedetails/get


to this: 

https://myqexternal.myqdevice.com/api/v4/UserDeviceDetails/Get

**Comment by Hyukishi** [comment]
After changing line 1028 to `apiGet("/api/v5/userdevicedetails/get", []) { response ->` I get the following, at which point it hangs again. Log below...

>
 bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug button devices to delete: []
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Chosen hub for child devices: SmartThings Hub (c4ba0bba-7adb-40ea-86ad-efbe241dbb15)
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug ID's to look for: [bf370c84-7fbc-4280-bf3c-3605c1993c1f|GarageDoorOpener|7855326 Opener, bf370c84-7fbc-4280-bf3c-3605c1993c1f|GarageDoorOpener|7855326 Closer]
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Found 1 hub(s) at this location.
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Valid hub found: SmartThings Hub (c4ba0bba-7adb-40ea-86ad-efbe241dbb15)
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Creating door with no sensor
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Creating child door device bf370c84-7fbc-4280-bf3c-3605c1993c1f|GarageDoorOpener|7855326
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug In CreateChild
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Storing door info: Garagetype: 17 status: 2 type: Garage Door Opener WGDO
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:43 AM: debug Found door: 7855326
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:42 AM: debug Initializing...
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:23 AM: debug Single door detected (string).
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:23 AM: debug Valid doors chosen: bf370c84-7fbc-4280-bf3c-3605c1993c1f|GarageDoorOpener|7855326
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:23 AM: debug Doors chosen: bf370c84-7fbc-4280-bf3c-3605c1993c1f|GarageDoorOpener|7855326
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug Storing door info: Garagetype: 17 status: 2 type: Garage Door Opener WGDO
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug Found door: 7855326
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug got login response: groovyx.net.http.HttpResponseDecorator@32be01bd
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug lightVersion: 1.0.1
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug doorNoSensorVersion: 1.1.8
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug doorVersion: 2.2.4
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug latestVersion: 2.1.6
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug installedVersion: 2.1.6
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug previousVersion: 2.1.6
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug lightVersion: 1.0.1
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug doorNoSensorVersion: 1.1.8
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug doorVersion: 2.2.4
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug latestVersion: 2.1.6
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug installedVersion: 2.1.6
bf370c84-7fbc-4280-bf3c-3605c1993c1f 10:41:09 AM: debug previousVersion: 2.1.6

**Comment by Hyukishi** [comment]
> Good news! I think I've got it working again. Just pushed an update.
> 
> Thankfully, the pymyq library (the one home assistance users) was not broken, so I was able to find the difference. Amazingly, it came down to something as simple as letter casing. I had to switch from this:
> 
> https://myqexternal.myqdevice.com/api/v4/userdevicedetails/get
> 
> to this:
> 
> https://myqexternal.myqdevice.com/api/v4/UserDeviceDetails/Get

I missed your reply right before posting mine... Gonna give it a shot :)

**Comment by brbeaird** [comment]
You just reminded me that URL is in more than one place. I need to fix that.

**Comment by Hyukishi** [comment]
Unfortunately, that didn't resolve the issue. Looks like like 1028 needs to show /api/v5/
userdevicedetails/get

**Comment by brbeaird** [comment]
Can you try the version I just pushed? Working for me in SmartThings now.

**Comment by brbeaird** [comment]
![image](https://user-images.githubusercontent.com/7239272/53583624-929d2600-3b47-11e9-8e82-f544afaad773.png)

**Comment by Hyukishi** [comment]
That worked! Thank you so much for your dedication to this project!

**Comment by guxdude** [comment]
Worked for me too! Thank you so much!

**Comment by brbeaird** [comment]
Awesome! Glad it was something simple.
