### ISSUE TITLE
devicetypes/ph4r/virtual-contact-sensor-switch.groovy

### ISSUE THREAD

**Issue by Jjbasso** [brbeaird/SmartThings_MyQ#6]
Just an fyi smart things will not load from engine.  There seems to be an error in it.  Not that I need it for garage doors but was easier to take all of your code when updating.

**Comment by brbeaird** [comment]
Thanks for pointing that out. The file was missing a containing folder (SmartThings is picky about file structure). It should be fixed now, so you can pull it down via the integration.
