### ISSUE TITLE
community installer is installing an old version  2.1.9 Current is 2.1.11

### ISSUE THREAD

**Issue by snowyogi** [brbeaird/SmartThings_MyQ#63]
My door stopped working as well. I tried re-installing with the community installer, but it is installing an old version (.9). I resolved the problem by installing from the repo which is .11

The response I got in the app is "username and password is incorrect"

9f097920-c286-4534-8bec-66b9dafe1081 1:42:52 PM: debug doorVersion: 2.2.4
9f097920-c286-4534-8bec-66b9dafe1081 1:42:52 PM: debug latestVersion: 2.1.11
9f097920-c286-4534-8bec-66b9dafe1081 1:42:52 PM: debug installedVersion: 2.1.9
9f097920-c286-4534-8bec-66b9dafe1081 1:42:52 PM: debug previousVersion: 2.1.9
9f097920-c286-4534-8bec-66b9dafe1081 1:42:51 PM: warn API POST Error: groovyx.net.http.ResponseParseException: OK
9f097920-c286-4534-8bec-66b9dafe1081 1:42:51 PM: trace Logging in

**Comment by brbeaird** [comment]
I updated the file -  should be updated now.
