### ISSUE TITLE
New smartthings app does not work with MyQ

### ISSUE THREAD

**Issue by farhanchaudhary** [brbeaird/SmartThings_MyQ#64]
I followed all the steps that brbeaird outlined to set up MyQ Garage control in smartthings app and it works great. Only problem is that when I click on the on/off button in the NEW smartthings app, the garage does not open or close. I see that in the OLD smartthings app, there's a open/close button and I can use it to open/close my garage door straight from smartthings. Why does it not work with the NEW smartthings app? Please fix! Thanks!

**Comment by brbeaird** [comment]
The new SmartThings app does not support custom SmartApps and devices handlers like this one. Nothing I can do about that, unfortunately. Supposedly that's coming one day, but it will be awhile. For now, the best thing to do is just keep using the Classic app for stuff like this.
