### ISSUE TITLE
Updated app doesn't show Open/Closed status from Smartthings multi-sensor

### ISSUE THREAD

**Issue by jeremyjhartley** [brbeaird/SmartThings_MyQ#65]
I had previously been using an old version of the app and it was working perfectly fine for me. I was messing around with some of my IDE settings and noticed that there was an updated version. I have no idea what the old version I had was. Anyway, after the update, I am not able to see the open/closed status even though I have a SmartThings multi-sensor which is set to be used as a garage door/tilt sensor. If I look at the sensor status, it says open or closes, but if I look at the garage door device, it doesn't see the status. I went through and made sure in the setup to have checked the accelerator sensor, but that didn't seem to work. Do I have to use a contact sensor with the new app?

**Comment by brbeaird** [comment]
I would not recommend using the accelerator sensor option - results are not super reliable with that.

The multi-sensor should work as a contact sensor.

**Comment by jeremyjhartley** [comment]
ok. I attached the magnet sensors so now it works as it should.
