### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by jsmith0103** [brbeaird/SmartThings_MyQ#66]
When I enter my correct MyQ credentials, I'm not able to log in. This just started happening in the last couple of days; not sure if there was some sort of update on their end. I have confirmed that the credentials are correct by logging out and back in via the official app.

Thank you!

**Comment by brbeaird** [comment]
Yep, MyQ made a change to the API on their end. I'm working on a fix now.

**Comment by adrian97c** [comment]
Thx for the quick upcoming fix Brian!


________________________________

**Comment by eric-a-katz** [comment]
I am having the same issue, anxiously looking forward to the fix, thx so much

**Comment by brbeaird** [comment]
Interestingly enough, at some point tonight MyQ reverted their change and brought the V4 API back up. The app should be working again (for now at least). I imagine they may try to kill it off again sometime in the future. As long as it's a day or two from now, I should have the SmartApp code ready to handle V5 so we'll be good to go.
