### ISSUE TITLE
Change icon for garage sensor in app

### ISSUE THREAD

**Issue by rogelioleon0221** [brbeaird/SmartThings_MyQ#67]
![Screenshot_20190808-105457_SmartThings](https://user-images.githubusercontent.com/53457146/62713868-6f668480-b9cb-11e9-9aed-d9c36221d30f.jpg)
![Screenshot_20190808-105443_SmartThings](https://user-images.githubusercontent.com/53457146/62713885-742b3880-b9cb-11e9-8c02-e7a6b3342e17.jpg)

I was just wondering if there was a way we can have different icons between the sensor and the garage door opener in the SmartThings app also have the garage door status removed from the sensor and replace it with temp to be main tile. Right now I have mine set up with MyQ being just garage door opener and using it specifically for door control and status and have the sensor as garage temp and using it specifically for checking temp but they both have the same icon which is a garage door and the sensor shows the door status as main tile when I'm really there just to check temp cause door status is shown in garage door section of app. Everything else is great and thank you.

**Comment by brbeaird** [comment]
I assume you're using a multi-sensor? That exists as its own device totally independent of the MyQ SmartApp - unfortunately, I don't think the SmartThings device handler gives you an option to choose which piece of information shows in the list. There may be some custom device handlers that add that ability, but I haven't looked lately.

Honestly, I would recommend against using the My Home tab in the app as a dashboard. It's pretty inflexible, and the more devices you add, the more annoying it is to check on something. Check out ActionTiles if you haven't already - that will give you exactly what you want as far as showing door control and sensor temp on the same screen.

**Comment by rogelioleon0221** [comment]
Thanks for fast response. So right now what I have in the new SmartThings app is garage door as a device and garage sensor. The garage door has two buttons that both control the door successfully and the garage sensor has no buttons but shows door status and garage temperature and yes this is a SmartThings multi-sensor setup as a garage sensor. I'm just wondering if that's the way it's supposed to be with the two buttons or if there's a way to get the garage door opener under the sensor.
![Screenshot_20190809-185706_SmartThings](https://user-images.githubusercontent.com/53457146/62813922-6e247d00-badb-11e9-97bf-f86eb1815f0c.jpg)
![Screenshot_20190809-185654_SmartThings](https://user-images.githubusercontent.com/53457146/62813926-72e93100-badb-11e9-8068-78e0c2bc162c.jpg)
![Screenshot_20190809-185629_SmartThings](https://user-images.githubusercontent.com/53457146/62813931-767cb800-badb-11e9-977d-b80b58377a31.jpg)

**Comment by adrian97c** [comment]
Same as Classic app. 👍🏽


________________________________

**Comment by rogelioleon0221** [comment]
Right now this is what the classic app looks like for me. With an open button close button and status of door which is pretty cool and works perfectly but as you can see in my earlier post it doesn't look like that in new SmartThings app where it just shows  door control button and garage door control which is different from classic app. so I'm curious if I did something wrong or is the new app supposed to say open and close and status. Is there a way for new app to display like classic?
![Screenshot_20190809-205029_SmartThings](https://user-images.githubusercontent.com/53457146/62815514-b8abf680-bae7-11e9-86c4-cdf9d99ee0f9.jpg)

**Comment by adrian97c** [comment]
I do see the extra button not shown in Classic... hmm heck mine look diff in my new app than your news... mine look like to big squares. Door control & Garage Door control.
[Image]

________________________________

**Comment by rogelioleon0221** [comment]
What does yours look like if you don't mind me asking for a screenshot? Looks like your image didn't come through.

**Comment by adrian97c** [comment]
I meant can’t figure out how to post pics here.


________________________________

**Comment by rogelioleon0221** [comment]
I had to be in desktop mode on my phone to post the screenshots you just tap where it says attach files by dragging and dropping selecting or pasting it's on bottom of this chat box.

**Comment by adrian97c** [comment]
![CEBDF712-0559-425C-A199-98FF32735A25](https://user-images.githubusercontent.com/35380549/62815831-73d68e80-baec-11e9-9399-ae1c31d5ebc1.png)

**Comment by rogelioleon0221** [comment]
Yeah I see what you mean now and honestly that's better than mine lol but thanks for sharing wonder what's different between the 2.

**Comment by adrian97c** [comment]
I have the newest, ST app update for iOS. Came out today. I’m running iOS 13 beta 6... & I’m using the latest MyQlite from this repo.


________________________________

**Comment by rogelioleon0221** [comment]
I have a Galaxy s8 plus so Android maybe it could be that
