### ISSUE TITLE
without” polling MyQ for status (which they will not allow done from the SmartThings cloud)“

### ISSUE THREAD

**Issue by lacedup** [brbeaird/SmartThings_MyQ#68]
How does homebridge and home assistant accomplish this?

**Comment by lacedup** [comment]
I use Hubitat. Basically Hubitat could do it since it’s local. Who can I pay to make this?

**Comment by brbeaird** [comment]
Not really sure on that one.  If I the day ever comes where I need to move platforms, I'll consider it, but it's not something I can do at the moment.
