### ISSUE TITLE
Unable to create SmartApp from code

### ISSUE THREAD

**Issue by tbubier** [brbeaird/SmartThings_MyQ#7]
I have tried both versions and was unable to create a SmartApp.  I received the following message:
"No signature of method: script14980567587321300469619.metadata() is applicable for argument types: (script14980567587321300469619$_run_closure1) values: [script14980567587321300469619$_run_closure1@5657c4e6] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)"
Please help.
Thanks,
Tim.

**Comment by brbeaird** [comment]
That error indicates you're trying to paste SmartApp code into a Device Handler (or vice versa). Make sure you're putting the right code type into the matching spot in the IDE.

**Comment by tbubier** [comment]
That was my error.  Just me jumping the gun and trying to create the Smart App before I had the Device Handlers saved.  Got it now. Thanks!
