### ISSUE TITLE
Chamberlin lights not working

### ISSUE THREAD

**Issue by Jamessmart1** [brbeaird/SmartThings_MyQ#72]
about three days ago everything worked great with the old program. updated to the new script and i get this error in live mode. "error API PUT Error: groovyx.net.http.HttpResponseException: Internal Server Error" the my q app works but the smarthing shows the device coming on and off but no response from the device.

**Comment by brbeaird** [comment]
Good news! I figured out the lamp module today, so the light device should work again. Check out the latest update and see if it that works for you.

**Comment by Jamessmart1** [comment]
It works. ThanksSent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Brian Beaird <notifications@github.com> Date: 10/21/19  1:12 PM  (GMT-08:00) To: brbeaird/SmartThings_MyQ <SmartThings_MyQ@noreply.github.com> Cc: Jamessmart1 <jsock2008@gmail.com>, Author <author@noreply.github.com> Subject: Re: [brbeaird/SmartThings_MyQ] Chamberlin lights not working (#72) Good news! I figured out the lamp module today, so the light device should work again. Check out the latest update and see if it that works for you.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brbeaird/SmartThings_MyQ/issues/72?email_source=notifications\u0026email_token=AIPNO2JSNJN4QEOFFHPKMVDQPYEMLA5CNFSM4JDB7WXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3UKPQ#issuecomment-544687422",
"url": "https://github.com/brbeaird/SmartThings_MyQ/issues/72?email_source=notifications\u0026email_token=AIPNO2JSNJN4QEOFFHPKMVDQPYEMLA5CNFSM4JDB7WXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3UKPQ#issuecomment-544687422",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jamessmart1** [comment]
I've been trying to figure this out but haven't been able to. Using Alexa
with voice commands only with my q devices you have to ask alexa to do the
function twice in order for it to work. sometimes it doesnt want to
respond. here is a set by step on live logging.
8:25:54 PM: debug Light turned on,  8:25:54 PM: warn Token has expired.
Logging in again, 8:25:55 PM: debug Got LOGIN POST response: STATUS:
200,8:25:55
PM: debug Got response: STATUS: 200,,8:25:55 PM: debug Got result: 0, 8:25:55
PM: debug got accountid, 8:25:55 PM: debug Got response: STATUS: 204, 8:25:55
PM: debug Updating status to on 8:25:54 PM: debug handlePostV3  8:25:54 PM:
debug Turn on Remote 8:25:54 PM: debug doesTvSupportVoice Remote:
false,  8:25:55
PM: debug routeEndpointEvent event name: switch, physical?: false 8:25:55 PM
: debug Property Changed event switch: on (source: DEVICE)  8:25:55 PM:
debug doesTvSupportVoice Remote: false  8:25:55 PM: info postEventToEndpoint:
event successfully posted.  8:25:55 PM: debug handlePostV3  *tried a
different device* 8:26:35 PM: warn Device type 'fan' unknown. Mapping to
'OTHER' instead. it came on first time.

**Comment by brbeaird** [comment]
That's really odd. Does that behavior only happen with Alexa?

I would expect some kind of error if the command isn't actually going through.

**Comment by Jamessmart1** [comment]
I have wipes out my smartthing handler, smartapp and all my q devices just
to have a fresh start. I have also removed the smarthing home skills and
devices on the alexa. I have a couple of devices that will not work with
voice commands(master bedroom fan and family room fan ect) so I created a
group and place those devices in separate groups and the voice commands
appear to work. The routines appears to work through the alexa app.The
smarthing app appears to work. Just an FYI these devices were named a year
ago maybe longer with your older program and they worked fine. The problem
seems to be related to the my q upgrade. I am still testing a couple more
circuits. If the live logging helps i can give you some more info on that.
I have not removed and reinstall these devices from the my q app yet.

**Comment by Jamessmart1** [comment]
I erased amazon alexa devices and everything with my q devices in the smartthing. I thought running routine work in alexa but it doesnt its intermittent. Also it appears that i have to inniate alexa twice to activate a my q device. I went to the my q app and realized on the old app if you select the device it turned on or off with a single touch. The new app you have to tap it twice in order to activate the device. This might be the issue. Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Brian Beaird <notifications@github.com> Date: 11/11/19  9:59 AM  (GMT-08:00) To: brbeaird/SmartThings_MyQ <SmartThings_MyQ@noreply.github.com> Cc: Jamessmart1 <jsock2008@gmail.com>, Author <author@noreply.github.com> Subject: Re: [brbeaird/SmartThings_MyQ] Chamberlin lights not working (#72) That's really odd. Does that behavior only happen with Alexa?
I would expect some kind of error if the command isn't actually going through.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brbeaird/SmartThings_MyQ/issues/72?email_source=notifications\u0026email_token=AIPNO2P3NP253V6TZLF4SEDQTGMRZA5CNFSM4JDB7WXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDXTQ5Q#issuecomment-552548470",
"url": "https://github.com/brbeaird/SmartThings_MyQ/issues/72?email_source=notifications\u0026email_token=AIPNO2P3NP253V6TZLF4SEDQTGMRZA5CNFSM4JDB7WXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDXTQ5Q#issuecomment-552548470",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rickjamess** [comment]
Have been having the same issue since updating the MyQ app. I have to give verbal command to Alexa twice to perform an action and have to tap the tile twice in the app to activate a light. My other issue is that the lights no longer turn on or off when the smart lighting app triggers them to turn on.

**Comment by brbeaird** [comment]
This is so odd. I tested mine last week, and it always works on the first try. Not quite sure what to tell you here unless you can get more detailed error log info.
