### ISSUE TITLE
Device Handler no longer working?

### ISSUE THREAD

**Issue by mbmclean** [brbeaird/SmartThings_MyQ#73]
The device handler hasn't been working for the past 1-2 months, but worked fine for almost a year prior.  Finally updated all of the code on my SmartThings IDE today, but still no luck.

Does this have anything to do with the MyQ app no longer being supported? 
 I didn't think it would since this is a workaround to get away from their software. 
 https://community.smartthings.com/t/discontinuation-of-myq-connect-community-smartapp/47183 

Thanks.

**Comment by brbeaird** [comment]
It's still supported and working. A big update was pushed a few weeks ago. It sounds like updating things in your environment didn't fully take. I'd suggest trying that again and maybe even just copy/pasting the app and handler code manually and publishing to force the update.
