### ISSUE TITLE
Device Handler and Community Installer Quirks

### ISSUE THREAD

**Issue by kc6108** [brbeaird/SmartThings_MyQ#74]
Basically these two ‘issues’ are just FYI as I’m not really encountering any issues in the MyQ Lite SmartApp.

#1:
When I go to update my device handlers for “SmartThings_MyQ“ I am presented with “devicetypes/brbeaird/myq-garage-door-opener.src/myq-lock-door.groovy” under “New (only in GitHub)”. I receive an error when I press “Execute Update” in order to add and publish the device handler. It seems there are two “myq-lock-door.groovy” files. The other is under “devicetypes/brbeaird/myq-lock-door.src” which I believe is the one I’m currently using for the ‘MyQ Lock Door’ device handler. I’m not sure what the difference is between the two groovy files?

Error received:

“Updated 0 devices and created 0 new devices, 0 published (1 skipped due to errors)“

#2:
Inside ST-Community-Installer, under MyQ Lite, the Device “Momentary Button Tile” shows uninstalled and won’t actually install if checked. Isn’t this device handler now obsolete or incorporated elsewhere?

**Comment by brbeaird** [comment]
> It seems there are two “myq-lock-door.groovy” files.

Oops. Yeah at some point I committed a duplicate. This should be removed now.



> the Device “Momentary Button Tile” shows uninstalled

Another good catch. I have moved that back under the same namespace as the others, and that should fix it going forward. Thanks.

**Comment by kc6108** [comment]
Everything seems to be back to normal. Thx
