### ISSUE TITLE
No doors listed in Smartapp

### ISSUE THREAD

**Issue by FMFDoc** [brbeaird/SmartThings_MyQ#75]
Good day,

Installed SmartThings_MyQ. Confirmed the app and all handlers are present, but I can't seem to get past the smartapp login screen. After adding the smartapp, I porvide my MyQ login info, chose my gateway brand and then hit the 'next' button. At that point I am presented with a blank screen. According to the install instructions I should be seeing a list of doors...

Any assistance you can provide would be greatly appreciated...

**Comment by adrian97c** [comment]
Make sure you don’t choose “Craftsman” that login nolonger works.


________________________________

**Comment by brbeaird** [comment]
You might also check live logging in the IDE while you walk through those steps.

One thing a lot of people have been running into is if they had a Craftmsan door and didn't migrate their account over to MyQ, this SmartApp isn't showing their devices. You apparently need to remove your doors from AssureLink and recreate in the native MyQ app first.
