### ISSUE TITLE
Status stuck in “opening”

### ISSUE THREAD

**Issue by airic101** [brbeaird/SmartThings_MyQ#77]
I got this integrated and the status was reflecting property showing open/closed when done with smart things, or even manually from the wall button. But the other day I tried to get Alexa to open the garage and I think it was at that point it got stuck in “opening” status, although that may not have been the case. Any ideas?

**Comment by airic101** [comment]
![5F825C5B-6144-4514-9276-6A0CE880F947](https://user-images.githubusercontent.com/58063450/69401638-d1b16f80-0cb2-11ea-8eb0-1efeca565945.jpeg)

**Comment by sphen13** [comment]
Been using this for years and just ran into the same thing. One door is stuck opening but all else shows it’s closed and up to date.

**Comment by brbeaird** [comment]
Does it do that when you're in the Classic app? Lots of little things like this still don't work quite right in the new app.

**Comment by sphen13** [comment]
It actually cleared up for me – could have been a temporary thing? I have been using the new app for at least 6+ months and it has been working well.

**Comment by apatulli** [comment]
I have same problem. I am using classic smarthings app. Garage door is stuck In Opening status.

**Comment by jeffrosenberg** [comment]
Same here, are there any logs that might be helpful to debug this? I'd be happy to help in any way I can.

**Comment by jeffrosenberg** [comment]
When I started investigating this further, I discovered that the multipurpose sensor I use was out of batteries. Replacing the battery fixed the issue. Oops! Does that solve anyone else's problem?

**Comment by brbeaird** [comment]
I'm pretty sure this means the link in the app between the door and sensor is broken. If you go back and tap through the setup process of selecting the sensor for the door and tap finish, it should resolve it.

At some point, I'd like to try and write some logic that detects this and repairs itself.
