### ISSUE TITLE
New IDE Partially Works

### ISSUE THREAD

**Issue by hautespotbob** [brbeaird/SmartThings_MyQ#78]
I copied the device handlers for "no sensor" garage door up to the new ST IDE (non classic) and was able to get it working mostly on the new app.

Problems discovered are: 

- Garage Door Opener and Garage Door Closer virtual devices (buttons) in app report "Cannot Connect to Device" error. Buttons do not work.
- Garage Door Device shows error "Checking Status". However if you open up the device and activate the door open and door close control, the door does open and close.
- Unable to use automations to actuate door operations. For example to have a motion detector in the garage open the door. Or for the door status (opened, closed, etc) to trigger another device.

Brian, now that ST supports custom smartapps and device handlers in the new IDE, would you be willing to revisit this project to get it working?  I don't have a lot of time to spend on this.

BTW, you can get the MYQ garage door opener hub controller for $29 on Amazon. Far less expensive than any other garage door opener control. 

You might be able to get MYQ to pay you for your work. I will donate.

Thanks, Bob

**Comment by brbeaird** [comment]
How did you do that? I thought the new IDE didn't run groovy?

**Comment by SteveA59** [comment]
I have the same issue, sorry I created a new issue Brian

**Comment by brbeaird** [comment]
Yes, I see what you both are talking about. The non-sensor version of this app does not seem to work in the new SmartThings app. Presumably this is because the non-sensor handler has garage door control but not a contact sensor attribute, and I guess the new app has no idea what to do with that. I'll play around and see what I can do.

**Comment by SteveA59** [comment]
Update, although they do not work direct in the Smartthings app, I linked the smartthings app with google home and the switches work perfectly I am just about to test voice activation

**Comment by brbeaird** [comment]
Right, the push-button (toggle) opener/closer switches definitely should still work, but the general garage door device is busted.

**Comment by SteveA59** [comment]
Not sure what you mean by busted , but the code works just not using the iPhone smart things app,

**Comment by brbeaird** [comment]
Busted as in the actual app probably looks like this:

![image](https://user-images.githubusercontent.com/7239272/73311283-b0598c00-41eb-11ea-97a6-71c1451e2c55.png)

**Comment by SteveA59** [comment]
It does but that button does work when you press it on the main smart apps page, its the open and close individual buttons that do not do anything, if that makes sense

I really appreciate you taking the time to reply as well

**Comment by brbeaird** [comment]
Gotcha. That's still pretty poor UI compared to the Classic app. I'll see what I can do.

**Comment by brbeaird** [comment]
I'll be pushing an update soon that should hopefully clean this up and simplify things.

**Comment by dmurchie** [comment]
Thank for the app! 
Just adding a vote on this issue:

- new ST app, no-sensor handler
- Generally able to open a door from the tile
- Tile always gets stuck on "checking status" or shows "unknown" after first tile button tap
- If I open the device (tap the tile off-button) and hit "Garage Door Control" button, will usually close door
- "Door Control" and "Garage Door Control" are pretty much always "unknown" (or broken cloud icon)
![IMG_67B17E9C1BE7-1](https://user-images.githubusercontent.com/9538982/128227732-ca21adb8-5ce6-408b-b47b-f003345db525.jpeg)

**Comment by brbeaird** [comment]
I just pushed an update that should help the no-sensor handler work a lot better.  Note: because of the weirdness of how custom device types work, you will likely not see the change take effect until you either delete the door device and re-add it or else go into the IDE and rename the door; even then, it may take up to an hour before you see the new icon in the app.

**Comment by SteveA59** [comment]
Hi Brian

Thanks for your continued work with this, What do I actually need to do to get the update (idiots guide please) I use Alexa to trigger the opening and closing, 

Steve A

**Comment by brbeaird** [comment]
You'll need to go to the new device handler code and copy/paste it into your SmartThings IDE.

If you read through the steps here, it should cover it: https://github.com/brbeaird/SmartThings_MyQ

**Comment by SteveA59** [comment]
All sorted many thanks

**Comment by SteveA59** [comment]
Hi Brian

MQ opener stopped working a couple of days ago any ideas ?
