### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by sjsjets** [brbeaird/SmartThings_MyQ#79]
My password does not work. The password line is populated by at least 10 periods which is longer than my password. How can I reset the password?  Do I have to uninstall everything, reset the opener and start from scratch?

**Comment by brbeaird** [comment]
You account info is manged by MyQ. If you had a Craftsman door with the AssureLink site, you may still need to migrate your account according to their instructions.

**Comment by sjsjets** [comment]
No - I had an old Raynor with a Go-Linear Z wave controller. The motor fell apart in September so I replaced it with a Chamberlin B970 (wifi and MyQ) and added an Ecolink Sensor. When I first set it up with an Aeotec door sensor on the door from the garage to the house to close the garage door when the den access door was closed.

When the motor was replaced last year I removed the linear control and sensor and added the Ecolink sensor. I think I used the Tonesto7 installer.

It seemed to work fine but then came garage door, garage door opener, garage door closer devices. Suddenly the garage door stopped closing. I used a combination of the the garage door and door closer but it doesn't work.

The real problem is somehow the MyQ password that works in the MyQ app started appearing in your Smartapp but looked twice as long as the real password. When I type in the MyQ app password in your Smartapp, it says it is the wrong password. I even changed the MyQ app password but it doesn't work.

I removed your Smartapp and reinstalled the new update. When I tried to enter the MyQ password, I still get a wrong password message. So I cannot log into your app to reconfigure it. Is there any way to permanently  delete the password or do I have to reset everything to new, including the opener and reinstall MyQ and your Smartapp?

**Comment by brbeaird** [comment]
The asterisks on the SmartApp login page do not represent the number of characters in your actual password - SmartThings keeps that hidden and just generically displays a bunch of characters.

Anytime you clear out the password field in the SmartApp and enter it in again, it saves it fresh, so the problem should not be that it's saving an old one.

Can you verify in the MyQ Lite SmartApp setup page what's under the version info section?

It might also be helpful to see the exact error message in the IDE Live Logging when you're trying to log in.
