### ISSUE TITLE
Can't find "My Apps" or "SmartThings Labs"

### ISSUE THREAD

**Issue by kylehayes** [brbeaird/SmartThings_MyQ#8]
The instructions state to find a My Apps section and the code says the category is SmartThings Labs. I can't find either in the mobile app and I wonder if this is due to the recent update that was released earlier this month.

**Comment by brbeaird** [comment]
What instructions are you looking at? That sounds like the old version. The current instructions say to go:
Automation -> SmartApps -> Add a SmartApp. Scroll down and tap My Apps. Tap MyQ Lite.

This does assume you've already added the code in your IDE - it will only show up after that's been added.

https://github.com/brbeaird/SmartThings_MyQ

**Comment by kylehayes** [comment]
It appears there was a problem with my account. You can close this issue because ST had to reset something. Thanks!
