### ISSUE TITLE
Updated to MyQ lite 3.1.1

### ISSUE THREAD

**Issue by apatulli** [brbeaird/SmartThings_MyQ#80]
Hello , update device handlers and smart app through IDE. 3.1.1. I then proceeded to smarthings classic apps to modify device and chose myq hub and a contact sensor.

It created 3 things in my home.  Garage Door(closed)  and Garage door opener(push) and Garage door closer.(push)

When I select either Garage door opener or Garage door closerer it works perfectly.

When I try to press on the 2 buttons inside Garage door(open or.close) , nothing happens ? Is this normal ? It just says opening ...

I just noticed SmartApp is 3.1.1 but Doordevice is 2.2.4...i did update through IDE should I update device handler manually?

I had previously installed this and don't recall device handlers I installed.

Now I have all 5 device handlers.
Momentary button tile, garage door opener, garage door opener nosensor , light switch, door lock.

Do I need all 5 device handlers installed ? What is difference with garage door opener and garage door opener nosensor? 

Thanks

**Comment by brbeaird** [comment]
Yes, it sounds like the door device update didn't take - might need a manual copy/paste on that one. I'd also recommend using the Community Installer.

If you've got sensors on the doors, you don't really need the momentary buttons - I'd suggest going through the setup again and unchecking that option.
