### ISSUE TITLE
Newbie 

### ISSUE THREAD

**Issue by Frankienunz83** [brbeaird/SmartThings_MyQ#81]
I am new to this... These instructions don't explain what to do with the code when I copy it in order to get it in smart things classic. I'm not even sure what code, Readme says code and handlers when I click on the link it sends me to a link that has about 16 files. We need all of them?

**Comment by brbeaird** [comment]
I'd suggest using the community installer: http://thingsthataresmart.wiki/index.php?title=Community_Installer_(Free_Marketplace)

Otherwise, go back to the Readme and scroll down to the word "Manual." If you follow each of those steps, you should get going.
