### ISSUE TITLE
API Post Error

### ISSUE THREAD

**Issue by tdoffing** [brbeaird/SmartThings_MyQ#82]
I am having an issue, and found a API post error in the live log. I'm not sure what I have broken to cause this issue. Any help is appreciated.

fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug lightVersion: 3.1.1
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug doorNoSensorVersion: 3.1.0
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug doorVersion: 3.1.1
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug latestVersion: 3.1.1
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug installedVersion: 2.1.11
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: debug previousVersion: 2.1.11
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: warn API POST Error:groovyx.net.http.HttpResponseException: Bad Request
fca4ca8a-1d05-4171-a5fa-581c2c2c6cfe 1:26:03 PM: trace Logging in

**Comment by brbeaird** [comment]
It looks like you have an outdated version installed. Update your SmartApp and Device Handler code, then step through the configuration again, and see if things improve.
