### ISSUE TITLE
Error logging in to MyQ account

### ISSUE THREAD

**Issue by ericadamkatz1** [brbeaird/SmartThings_MyQ#83]
Starting today, I am getting notifications that Smartthings can no longer looking in to my MyQ account.  Hoping it's something simple.  I haven't changed my configuration in months.

**Comment by bracken898** [comment]
I'm getting the same notifications. Hoping it's an easy fix.

**Comment by brbeaird** [comment]
Yeah, I'd suggest going into the SmartApp setup, then clearing and re-entering your login info.

**Comment by sjsjets** [comment]
It kept saying the password was wrong. I reset it and when I logged in the password was wrong again. After I did it it at least six more times until it finally took. Then when I tried it with the smart app, I got error messages. I had the lastest app and handler installed.

**Comment by vpuglisijr** [comment]
I'm having the same issue. I installed today. It works for about 15 minutes then it gives me the message "Warning: MyQ command failed due o a bad login." I have reset it about 5 times with the same results.

**Comment by ikonis** [comment]
Can confirm... cannot login with known correct login information. Uninstalled smartapp and reinstalled.... no dice

**Comment by adrian97c** [comment]
[Image]

________________________________

**Comment by brbeaird** [comment]
MyQ was having issues on Thursday across the board, but it should all be back working again now.

If you're able to login via the native MyQ app but not with this SmartApp and you can verify the version shows "latest" installed, the only other thing I can think of is to set your password to something temporary and e-mail it to me so I can try to login with it over the API to see what's happening.
