### ISSUE TITLE
Door Control vs Garage Door Control

### ISSUE THREAD

**Issue by gcc235** [brbeaird/SmartThings_MyQ#84]
I was just wondering, why there’s Door control and Garage Door Control instead of just having one.  I can open the garage door with either Door control or Garage Door Control but I can only close use the Garage Door control.  I’m curious, what’s the Door control for.  Thanks.

**Comment by brbeaird** [comment]
There are other apps that are hard-coded to use one or the other. Having both capabilities on the device makes it play better with multiple other SmatApps.
