### ISSUE TITLE
Can see items in smart things and even when integrated into Google home it shows devices but none show up in home?

### ISSUE THREAD

**Issue by TTVert** [brbeaird/SmartThings_MyQ#86]
I have tried to remove and reassociate smart things w/ google home but they never show up.  Going into home control in google home under smartthings all i see are the preconfigured routines "good morning, good night, goodby and I'm back" so I know integration but isn't showing this door switches.  Anyone else run into this before?

Thanks
Dave

**Comment by brbeaird** [comment]
Last I heard, Google Home does not show garage door devices due to security.

As a workaround, you can use the option to create push button "opener" devices - those should show up in Google as simple switches you can "turn on" to trigger the door to open.

**Comment by TTVert** [comment]
Yeah that is what I ended up having to do.  Have you guys ever gotten the scenes to work w/ google?   
 I seem to recall reading something about them (I think here) and that they may be buggy or not even work?Under IFTTT in SmartThings I don't have the option to enable anything other than my switches.  I doubt that is the place to even be in but i figured I'd look.  I did sort of get it working in google home under assistant settings | assistant | Routines but was wondering if there was a way to use the native scenes? 

Dave

**Comment by brbeaird** [comment]
Scenes do work, but last I checked, it's a terrible process. From Google Home, tap routines => manage => Add New => Choose trigger => Add Action => popular actions => Adjust scenes => gear => Choose your scene.

It's buried waaaaay down in there.

**Comment by phaldor8** [comment]
And this is exactly why I use IFTTT....SOOO much simpler to create a
trigger there that talks to Google.


Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130
