### ISSUE TITLE
Door sensor issues 

### ISSUE THREAD

**Issue by mayurpatel77** [brbeaird/SmartThings_MyQ#87]
I've uninstalled and reinstalled and also tried every setting I could and can't get my door sensor to be recognized. Any guidance would be appreciated. Here are screenshots:

![Screenshot_20200104-162757](https://user-images.githubusercontent.com/32936959/71772413-3bf33c00-2f10-11ea-9da3-2d56d159c1c1.png)

![Screenshot_20200104-162820](https://user-images.githubusercontent.com/32936959/71772422-50cfcf80-2f10-11ea-8379-4061000a5874.png)

![Screenshot_20200104-162940](https://user-images.githubusercontent.com/32936959/71772425-575e4700-2f10-11ea-8479-e9fea0a6681f.png)

![Screenshot_20200104-163218](https://user-images.githubusercontent.com/32936959/71772427-5decbe80-2f10-11ea-892d-b1688610227a.png)

![Screenshot_20200104-163348](https://user-images.githubusercontent.com/32936959/71772430-647b3600-2f10-11ea-981b-ec89bb2d45a3.png)

**Comment by brbeaird** [comment]
Weird. You have just a single door? Do you see anything in IDE Live Logging while tapping through the setup process?

You also might try checking the config state details:

My Locations -> installed smartapps -> scroll down to MyQ Lite and click it

I'd be curious if you have anything under door1Sensor.

**Comment by mayurpatel77** [comment]
I have 3 MyQ devices, 2 garage door openers and a a gate opener.  I've only attached a sensor to one garage door - "Main Garage".

I just removed all 3 and re-added them.  Everything looks like the previous screenshots. 

Here are screenshot of the logs and from config state  (sorry for the black outs, not sure if I should be exposing those identifiers):

![image](https://user-images.githubusercontent.com/32936959/71839475-d8d4e700-3080-11ea-8b77-65f4704f9b3b.png)

![image](https://user-images.githubusercontent.com/32936959/71839558-0ae64900-3081-11ea-8583-db9397333b57.png)

**Comment by mayurpatel77** [comment]
Update! Turns out I didn't try everything. I went through setup and removed all of the doors and then went back through and only added the door with the sensor. It works! I then went through setup two more items adding the other doors one at a time and it still works.

Screenshots:
![Screenshot_20200106-124441](https://user-images.githubusercontent.com/32936959/71840538-1e92af00-3083-11ea-9a5d-a709de5e67b2.png)

![Screenshot_20200106-124617](https://user-images.githubusercontent.com/32936959/71840547-23576300-3083-11ea-95f1-1989140be408.png)

**Comment by brbeaird** [comment]
Yep, this is what I thought might be happening - you found a bug.

The app assumes that if you have at least one sensor that the first door added will have one. That's not a perfect assumption. I'll see about updating that. Glad you got it working, though!

**Comment by brbeaird** [comment]
I believe this is fixed with my latest commit. The logic should more cleanly determine if sensors are in use regardless of whether or not the first door happens to have one.
