### ISSUE TITLE
Door Doesn't Open

### ISSUE THREAD

**Issue by jpsecure** [brbeaird/SmartThings_MyQ#88]
I have updated both the SmartApp and the Device Handlers. Gone through the account login steps. No errors appear.  When I push the "Open" tile, it shows as "Opening", but nothing happens. When I click on the "Recently" tab it lists "Sent Opening Command".

On the "Right Now" tab it shows the status as "Opening" with the "Last Activity" of the date and time when I updated the code...

I have a separate door sensor and have tried both turning on and off "Create on/off push buttons".  I can open and close the door using the MyQ app.

Would appreciate any assistance you can offer to get this functioning within SmartThings...

**Comment by iboje** [comment]
Hey jpsecure, I think I'm having this issue too.  What troubleshooting have you done?  I haven't gotten around to it yet.

**Comment by brbeaird** [comment]
After you updated the code, did you tap through the door config steps?

Do you see anything in the IDE live logging when you try and open it?

**Comment by iboje** [comment]
I didn't update, unless it auto-updated.  I went ahead and went through the steps anyway.  At the end, it said the device was already added.

Checked logs, and I'm confused by what I see:
2020-01-23 12:04:50.116 PM CST close command was sent to Garage Door
2020-01-23 12:04:49.906 PM CST Garage door close command called.

That seems weird, because the door is wrong.  I wonder if the sensor is acting up.  It does show that the door is closed.

**Comment by brbeaird** [comment]
When you open the SmartApp setup and scroll down to versions, does it show the app and handlers as the latest version?

**Comment by iboje** [comment]
It looked like it.  When I arrived home today, it seemed to work fine.  I'm not sure what happened; perhaps re-doing the setup fixed it.  Thanks for the tip.

On to my next problem: Alexa is spouting off some strange gibberish.

**Comment by iboje** [comment]
I spoke too soon, it seems like it isn't working for me, but I think the issue is with the MyQ hardware.  I'm not able to control my door using their native app.  I'd be interested to hear if the same issue is happening to @jpsecure

**Comment by jpsecure** [comment]
Brian,

I did tap through the door config steps and completed with no errors.

When I tap "open" the IDE log shows:

3:41:02 PM: debug Garage door open command called.

SmartApp setup shows:  SmartApp 3.1.1 (latest) & DoorDevice 3.1.1 (latest)

Thanks for any advice...

Joe Poli

________________________________

**Comment by jpsecure** [comment]
I have tried deleting and re-installing the SmartApp, and also updated the SmartApp and Device Handler code.  Then stepped through all the config items selecting the door, sensor, etc.

I am able to control the door from the MyQ App...


Joe Poli

________________________________
