### ISSUE TITLE
Buttons say "Cant connect to device" Check Connection

### ISSUE THREAD

**Issue by SteveA59** [brbeaird/SmartThings_MyQ#89]
Hi Brian, I have a MyQ door with no sensors, I followed the instructions from https://github.com/brbeaird/SmartThings_MyQ
Its a door with no sensors so I added the momentary buttons, but they do nothing when pressed , just say cannot connect to device 
The Garage Door Opener main button works and returns the "unknown" status as specified, it opens and closes

Any help to a complete novice would be appreciated

**Comment by SteveA59** [comment]
Update, although they do not work direct in the Smartthings app, I linked the smartthings app with google home and the switches work perfectly I am just about to test voice activation

**Comment by SteveA59** [comment]
Voice Activation works fine

**Comment by jwhardcastle** [comment]
+1 for this, I added the ST code using the manual method (SmartApp, momentary button, no-sensor DH) to use with my Chamberlain integrated door (no tilt sensor). Doesn't work in the Smarter Things app, but does work in the Google Home app, and by using Google Assistant with voice.

I'm done, all I wanted was control from Google, which I have, but just in case others come across this.

**Comment by brbeaird** [comment]
Thanks for the info. Things are definitely in a weird place at the moment while SmartThings is transitioning to the new app.
