### ISSUE TITLE
Working with MyQ's own sensor

### ISSUE THREAD

**Issue by premanandc** [brbeaird/SmartThings_MyQ#9]
Thanks for writing this integration. It is very useful. This is more a question, rather than an issue. Is it possible to use MyQ's own [sensor](https://smile.amazon.com/Chamberlain-Universal-MYQ-G0202-MYQ-G0201-Separately/dp/B00NO1K6QU/ref=pd_bxgy_60_img_2) to work?

If so, can you please help?

Thanks!

**Comment by brbeaird** [comment]
No, not that I know of. There's no way to access the sensor directly. All it does is report the open/closed status directly to the MyQ servers.

**Comment by premanandc** [comment]
Thanks for the clarification. I'll get a z-wave plus compatible tilt sensor like the one you recommend.
