### ISSUE TITLE
"Could not find any supported device(s)"

### ISSUE THREAD

**Issue by dbedwell** [brbeaird/SmartThings_MyQ#90]
I updated to the latest version and am getting this error when I add the Smart App to Smartthings and log in. I've removed all device handlers and apps and added again with the latest but still get the error. I see from a previous issue that somebody else had this issue a while back and the cause was different versions of code across different MyQ cloud shares.  What's the easiest way to make sure everything is synced? What else could be causing the problem?

**Comment by brbeaird** [comment]
When you open the SmartThings mobile app now and then go into the MyQ Lite SmartApp setup, you should be able to scroll down and see installed version numbers along with a note indicating if it's the latest version. If you're on the latest and still seeing this, I can take a closer look if you want. It might also be helpful to check the IDE Live logging when you're trying to click through the device setup steps.

**Comment by brbeaird** [comment]
Let me know if you want me to dig deeper into it.
