### ISSUE TITLE
Getting exception error at end of application setup

### ISSUE THREAD

**Issue by Tsurnick** [brbeaird/SmartThings_MyQ#91]
I am excited to see so many people get this working.  I have an MYQ-G0301 which comes included with a door sensor.  I went through the instructions and everything worked fine, until after I logged into the application on the phone. After signing in you go through the selections, and when I click done at the end I got the following error:
![Screenshot_20200209-040341_SmartThings](https://user-images.githubusercontent.com/50520023/74101274-28865280-4b06-11ea-9942-f6cc29a54d0a.jpg)

I am really hoping to get this working.  It would be awesome. 
Thank you in advance for the work you put into this project.  I think it is awesome.
Thanks
Thomas

**Comment by apottere** [comment]
I'm getting this error as well in the new ST app.  I followed the guide here to add a simulated contact sensor for the garage door: https://community.smartthings.com/t/how-to-smartthings-myq-smartapp-using-myq-sensors-with-ifttt/149601

**Comment by apottere** [comment]
This is because I didn't install the device handlers in addition to the smartapp /facepalm

**Comment by brbeaird** [comment]
Glad you got it figured out!

**Comment by Tsurnick** [comment]
Hi Brian, Andrew resolved his issue, but I tried the same thing without success.
Any suggestions? Thanks

**Comment by brbeaird** [comment]
That error indicates you don't have the latest device handler for the door. If you can get that code update and published to your IDE and try it again, I think you'll have better luck.

**Comment by Tsurnick** [comment]
Thanks.  I will work on the device handler.  I knew it had to be something simple.
Appreciate your help.
