### ISSUE TITLE
Question regarding need for sensor

### ISSUE THREAD

**Issue by entmike** [brbeaird/SmartThings_MyQ#92]
Hello!

I'm currently using the SmartThings_MyQ Smart App without a sensor, understanding that there is a limitation of being able to derive the status of the door.

My question is, is this a limitation in SmartThings or just this smart app?  The reason I am asking is I am also playing with `homebridge-myq` to bridge over devices to HomeKit, and I've noticed that it does successfully manage to detect garage state without the need of another sensor.

The project is here, in case similar logic could be used in your project.

https://github.com/caseywebdev/homebridge-chamberlain.

Code:

https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/chamberlain-accessory.js

**Comment by brbeaird** [comment]
It is a limitation of SmartThings and MyQ. Several years ago, the original version of the app used polling to periodically get the status of the door. SmartThings intervened and disabled that app's ability to do that, and because of that, I wrote this version that uses a local sensor instead.
