### ISSUE TITLE
Change Device Icon

### ISSUE THREAD

**Issue by kevinjonsutton** [brbeaird/SmartThings_MyQ#93]
I installed the smart app and it is working perfectly on the new SmartThings app. The only thing is the device icon that shows up is a sensor icon instead of a garage door icon. Is there a way you can update the app so it shows a garage door icon for the DH instead? This would make things less confusing when controlling my devices from the app. Couldn't find a way to do this my self. I am using the MyQ Garage Door Opener device handler with the sensor. Thanks! 

![IMG_0124](https://user-images.githubusercontent.com/45573456/74990395-122aa180-53f8-11ea-9571-da1d3cd115aa.PNG)

**Comment by brbeaird** [comment]
This is a major downside of the new app - we have basically no control over how things display. Hopefully they'll add more customization in the future.
