### ISSUE TITLE
Question Really .... ST Multipurpose Sensor use Tilt

### ISSUE THREAD

**Issue by ThatGuyDogboy** [brbeaird/SmartThings_MyQ#94]
Hey,

I'm just getting into the MyQ Lite app and I purchased the SmartThings Multipurpose Sensor.

For me, it's difficult to get these sensors to actual "Open" and "Close" on my doors. I was wondering if there is a way to use the tilt sensor instead?

**Comment by brbeaird** [comment]
The tilt sensor mode should also work fine - it's just a matter of setting up the sensor as being on a garage door I think.

Keep in mind, you won't be able to go into the sensor itself to control the door - once you go through the SmartApp setup, it will create a garage door device in your list, and you can control the door from that device.
