### ISSUE TITLE
MyQ Not Responding to Commands

### ISSUE THREAD

**Issue by jdtoth** [brbeaird/SmartThings_MyQ#95]
Looks like this is getting stuck when sending a command to the MyQ API to open the device. In ST, the status changes to "Opening", and the garage door doesn't open. 

I checked the logs and I'm getting back a 204 status. Is a 204 the expected response or is something wrong? Snip of my logs below:

Got LOGIN POST response: STATUS: 200
Got response: STATUS: 200
Got result: 0
got accountid xx-xx-xx-xx-xx
Got response: STATUS: 204

**Comment by jdtoth** [comment]
I think this is a hardware problem. Can someone else confirm that the service is functioning for them?

**Comment by brbeaird** [comment]
You still getting this? Things are working fine for me.

**Comment by jdtoth** [comment]
It's working again, I think their API or my account was the issue. It mysteriously started working again several days later and I changed nothing.
