### ISSUE TITLE
Door stuck half open

### ISSUE THREAD

**Issue by jasonmadigan** [brbeaird/SmartThings_MyQ#96]
Am using with the "MyQ Premium with IFTTT and Virtual Sensors" config. All OK, but occasionally I've noticed that my door opens half way and then pauses/stops. Wondering if I've misconfigured something or if anyone else has seen similar

**Comment by brbeaird** [comment]
That does not sound related to this integration, but I can't say for sure as I'm not using IFTTT. You could try checking logs in IFTTT to verify something isn't sending two commands that might cause it to pause.
