### ISSUE TITLE
Since last year myq lite will not allow login

### ISSUE THREAD

**Issue by araczek** [brbeaird/SmartThings_MyQ#98]
I am using the classic app, I removed everything at least 3 to four times in both smartthings and in the ide,  and still have this error, not accepting my username and password which works in the Chamberlin app. Honestly I bought this opener (Chamberlin) so I could use the app in Smartthings. I know Chamberlin updated the api so is there any updates that can fix this? 
Rather frustrating.
Note this worked fine before the API change.

Alan

**Comment by brbeaird** [comment]
It's still working for lots of us. The only thing I can think of is that you don't have the latest SmartApp or door handler code. When you open the SmartApp, what versions does it show towards the bottom?

**Comment by araczek** [comment]
> It's still working for lots of us. The only thing I can think of is that you don't have the latest SmartApp or door handler code. When you open the SmartApp, what versions does it show towards the bottom?

Are you talking about version on iPhone app or in ide? In app on phone there is no way to see a version if I can’t log in. I have removed everything, smartapps and device handlers , removed and re added with no luck. I had also removed the app.

**Comment by bherbst** [comment]
I had a similar issue (it had been working fine and stopped working sometime in the last few months). I think it was a problem with special characters in my password. Not sure which character it was, but I changed my password to something without special characters and it is working fine now.
