### ISSUE TITLE
Unknown Status / Light control / additional features

### ISSUE THREAD

**Issue by SamSamm13** [brbeaird/SmartThings_MyQ#99]
Sorry if these questions have already been asked, I'm a bit new to the tech scene.

1) on my ST app, i see the status as unknown for the garage opener. It's my understanding we'd need a ST capable sensor installed on the garage door in order to determine the status of the door? Just to confirm, this is different than the sensors that come with the standard garage that prevent it from closing on something? How would we go about setting up that sensor so it syncs within the MyQ lite SmartApp?

2) is there a way to control the lamp light that is built in the garage motor fixture?

3) I was seeing folks utilize additional capabilities. Not sure if this is possible, but would we be able to set up features like opening the garage door when someone's phone approaches the house?  Or would that have to be worked in with the automation feature of ST app? On my ST tile for the garage door(through MyQ Lite) I see door control and garage door control. Was not sure if I should be able to see additional features here?

Sorry for all the questions!

Thank you so much for all your help, i really do appreciate it!

![Screenshot1](https://user-images.githubusercontent.com/65405603/82061389-a5414380-9696-11ea-8e7b-6a3b51900ac6.png)

**Comment by brbeaird** [comment]
There is very little we can do with it in the new SmartThings app. It's more fully supported in the Classic app.
